# $FreeBSD$

PORTNAME=	http-client-conduit
PORTVERSION=	0.2.0.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Frontend support for using http-client with conduit

LICENSE=	MIT

USE_CABAL=	conduit http-client>=0.2 resourcet>=0.4.6 transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
