# New ports collection makefile for:	hs-data-accessor-monads-fd
# Date created:		December 8, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	data-accessor-monads-fd
PORTVERSION=	0.2.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Accessor to access state in monads-fd State monad class

LICENSE=	BSD

USE_CABAL=	data-accessor>=0.2 monads-fd>=0.1 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
