# $FreeBSD$

PORTNAME=	hashable
PORTVERSION=	1.1.2.5
PORTEPOCH=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Class for types that can be converted to a hash value

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
