# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-show/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	show
PORTVERSION=	0.6
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	'Show' instances for Lambdabot

LICENSE=	GPLv2

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
