# New ports collection makefile for: hs-concrete-typerep
# Date created:        December 8, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	concrete-typerep
PORTVERSION=	0.1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary and Hashable instances for TypeRep

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	binary hashable

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
