# $FreeBSD$

PORTNAME=	concrete-typerep
PORTVERSION=	0.1.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary and Hashable instances for TypeRep

LICENSE=	BSD

USE_CABAL=	hashable

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
