# $FreeBSD$

PORTNAME=	vado
PORTVERSION=	0.0.5
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Runs commands on remote machines using ssh

LICENSE=	MIT

USE_CABAL=	attoparsec>=0.10.4.0 text>=0.11.3.1

EXECUTABLE=	vado vamount

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
