# New ports collection makefile for: hs-data-lens-template
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-data-lens-template/Makefile,v 1.2 2012/06/03 22:13:35 pgj Exp $
#

PORTNAME=	data-lens-template
PORTVERSION=	2.1.5
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for Data.Lens

LICENSE=	BSD

USE_CABAL=	data-lens>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
