# $FreeBSD$

PORTNAME=	test-framework-th
PORTVERSION=	0.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Automagically generate the HUnit- and Quickcheck-bulk-code using Template Haskell

LICENSE=	BSD

USE_CABAL=	haskell-src-exts language-haskell-extract>=0.2 regex-posix \
		test-framework

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
