# $FreeBSD: head/net/hs-network-info/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	network-info
PORTVERSION=	0.2.0.7
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access the local computer's basic network configuration

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
