# $FreeBSD: head/devel/hs-activehs-base/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	activehs-base
PORTVERSION=	0.3.0.2
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic definitions for activehs

LICENSE=	BSD3CLAUSE

USE_CABAL=	QuickCheck>=2.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
