# New ports collection makefile for: hs-activehs-base
# Date created:        June 25, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	activehs-base
PORTVERSION=	0.3.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic definitions for activehs

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	QuickCheck>=2.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
