# Created by: jyyou@cs.nctu.edu.tw
# $FreeBSD: head/databases/hs-mysql/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	mysql
PORTVERSION=	0.1.1.8
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level MySQL client library

LICENSE=	BSD3CLAUSE

USE_MYSQL=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
