# New ports collection makefile for:	hs-mysql
# Date created:		2011-05-23
# Whom:			jyyou@cs.nctu.edu.tw
#
# $FreeBSD: head/databases/hs-mysql/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	mysql
PORTVERSION=	0.1.1.4
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A low-level MySQL client library

LICENSE=	BSD

USE_MYSQL=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
