# New ports collection makefile for:	hs-mysql
# Date created:		2011-05-23
# Whom:			jyyou@cs.nctu.edu.tw
#
# $FreeBSD: ports/databases/hs-mysql/Makefile,v 1.2 2012/02/13 04:07:07 pgj Exp $
#

PORTNAME=	mysql
PORTVERSION=	0.1.1.3
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A low-level client library for the MySQL database

LICENSE=	BSD

USE_MYSQL=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
