# New ports collection makefile for: hs-HStringTemplate
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-HStringTemplate/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	HStringTemplate
PORTVERSION=	0.6.8
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	StringTemplate implementation in Haskell

LICENSE=	BSD

USE_CABAL=	parsec syb text utf8-string

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
