# $FreeBSD$

PORTNAME=	HStringTemplate
PORTVERSION=	0.6.11
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	StringTemplate implementation in Haskell

LICENSE=	BSD

USE_CABAL=	blaze-builder dlist>=0.2 mtl parsec syb syb-with-class \
		text utf8-string

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
