# $FreeBSD$

PORTNAME=	oo-prototypes
PORTVERSION=	0.1.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for OO-like prototypes

LICENSE=	GPLv2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
