# $FreeBSD$

PORTNAME=	llvm-general-pure
PORTVERSION=	3.3.8.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure Haskell LLVM functionality (no FFI)

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0.1.0 parsec>=3.1.3 setenv>=0.1.0 transformers>=0.3.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
