# New ports collection makefile for: hs-StateVar
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-StateVar/Makefile,v 1.7 2012/06/03 20:52:09 pgj Exp $
#

PORTNAME=	StateVar
PORTVERSION=	1.0.0.0
PORTREVISION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	State variables for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
