# $FreeBSD: head/devel/hs-StateVar/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	StateVar
PORTVERSION=	1.1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	State variables

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
