# $FreeBSD$

PORTNAME=	pointedlist
PORTVERSION=	0.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Zipper-like comonad which works as a list, tracking a position

LICENSE=	BSD

USE_CABAL=	binary derive

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
