# New ports collection makefile for:	hs-pointedlist
# Date created:		December 8, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	pointedlist
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A zipper-like comonad which works as a list, tracking a position

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	data-accessor

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
