# $FreeBSD$

PORTNAME=	annotated-wl-pprint
PORTVERSION=	0.6.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Wadler/Leijen Pretty Printer, with annotation support

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
