# $FreeBSD$

PORTNAME=	language-haskell-extract
PORTVERSION=	0.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Module to automatically extract functions from the local code

LICENSE=	BSD3CLAUSE

USE_CABAL=	regex-posix

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
