# New ports collection makefile for: hs-recaptcha
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-recaptcha/Makefile,v 1.2 2012/06/03 20:52:27 pgj Exp $
#

PORTNAME=	recaptcha
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Functions for using the reCAPTCHA service in web applications

LICENSE=	BSD

USE_CABAL=	HTTP>=3001.1.4 network>=2.2.0.1 xhtml>=3000.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
