# $FreeBSD: head/devel/hs-cereal/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cereal
PORTVERSION=	0.4.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary serialization library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
