# New ports collection makefile for:	hs-cereal
# Date created:		2010-08-17
# Whom:			Ashish SHUKLA <ashish@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-cereal/Makefile,v 1.2 2012/02/13 04:21:49 pgj Exp $
#

PORTNAME=	cereal
PORTVERSION=	0.3.5.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A binary serialization library for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
