# $FreeBSD: head/textproc/hs-uri/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	uri
PORTVERSION=	0.1.6.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for working with URIs

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=3.0 safe utf8-string

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
