# $FreeBSD: head/devel/hs-word8/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	word8
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Word8 library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
