# New ports collection makefile for:	hs-data-default
# Date created:		2011-03-07
# Whom:			Ashish SHUKLA <ashish@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-data-default/Makefile,v 1.3 2012/06/03 21:39:31 pgj Exp $
#

PORTNAME=	data-default
PORTVERSION=	0.4.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A class for types with a default value for Haskell

LICENSE=	BSD

USE_CABAL=	dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
