# $FreeBSD: head/devel/hs-data-default/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-default
PORTVERSION=	0.5.3
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Class for types with a default value

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class data-default-instances-base \
		data-default-instances-containers data-default-instances-dlist \
		data-default-instances-old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
