# New ports collection makefile for:	hs-data-default
# Date created:		2011-03-07
# Whom:			Ashish SHUKLA <ashish@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	data-default
PORTVERSION=	0.2.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A class for types with a default value for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
