# $FreeBSD$

PORTNAME=	pointed
PORTVERSION=	4.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pointed and copointed data

LICENSE=	BSD

USE_CABAL=	comonad>=4 data-default-class>=0.0.1 semigroupoids>=4 \
		semigroups>=0.8.3.1 stm>=2.1.2.1 tagged>=0.5 \
		transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
