# $FreeBSD: head/devel/hs-async/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	async
PORTVERSION=	2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Run IO operations asynchronously and wait for their results

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm>=2.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
