# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/devel/hs-Stream/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	Stream
PORTVERSION=	0.4.7.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for manipulating infinite lists

LICENSE=	BSD3CLAUSE

USE_CABAL=	lazysmallcheck>=0.3 QuickCheck>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
