# New ports collection makefile for:	Stream
# Date created:				November 26, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: ports/devel/hs-Stream/Makefile,v 1.10 2011/05/26 00:50:55 ashish Exp $

PORTNAME=	Stream
PORTVERSION=	0.4.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for manipulating infinite lists

LICENSE=	BSD

USE_CABAL=	lazysmallcheck>=0.3 QuickCheck>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
