# New ports collection makefile for:	Stream
# Date created:				November 26, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: ports/devel/hs-Stream/Makefile,v 1.8 2010/05/12 16:33:39 pgj Exp $

PORTNAME=	Stream
PORTVERSION=	0.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for manipulating infinite lists

LICENSE=	BSD

USE_CABAL=	lazysmallcheck>=0.3 QuickCheck>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
