# $FreeBSD$

PORTNAME=	cryptohash
PORTVERSION=	0.9.1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Collection of crypto hashes, fast, pure, and practical

LICENSE=	BSD

USE_CABAL=	byteable cereal>=0.2 crypto-api>=0.5 tagged>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
