# $FreeBSD: head/security/hs-cryptohash/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cryptohash
PORTVERSION=	0.11.6
PORTREVISION=	2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Collection of crypto hashes, fast, pure, and practical

LICENSE=	BSD3CLAUSE

USE_CABAL=	byteable

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
