# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/math/hs-probability/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	probability
PORTVERSION=	0.2.4.1
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Probabilistic Functional Programming

LICENSE=	BSD3CLAUSE

USE_CABAL=	random>=1.0 utility-ht>=0.0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
