# New ports collection makefile for: hs-probability
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/math/hs-probability/Makefile,v 1.6 2011/05/26 00:51:07 ashish Exp $
#

PORTNAME=	probability
PORTVERSION=	0.2.3.1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Probabilistic Functional Programming

LICENSE=	BSD
FILE_LICENSE=	COPYRIGHT

USE_CABAL=	transformers>=0.0.1 utility-ht>=0.0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
