# New ports collection makefile for: hs-probability
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/math/hs-probability/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	probability
PORTVERSION=	0.2.4
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Probabilistic Functional Programming

LICENSE=	BSD
FILE_LICENSE=	COPYRIGHT

USE_CABAL=	random>=1.0 transformers>=0.0.1 utility-ht>=0.0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
