# $FreeBSD: head/security/hs-cryptohash-conduit/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cryptohash-conduit
PORTVERSION=	0.1.1
PORTREVISION=	2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cryptohash conduit

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit conduit-extra cryptohash resourcet

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
