# $FreeBSD: head/devel/hs-monad-loops/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	monad-loops
PORTVERSION=	0.4.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monadic loops

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
