# $FreeBSD: head/devel/hs-unordered-containers/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	unordered-containers
PORTVERSION=	0.2.5.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient hashing-based container types

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.0.1.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
