# New ports collection makefile for: hs-plugins
# Date created:        January 25, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	plugins
PORTVERSION=	1.5.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Dynamic linking for Haskell and C objects

LICENSE=	BSD

USE_CABAL=	ghc-paths haskell-src random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
