# $FreeBSD: head/devel/hs-blaze-builder-enumerator/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	blaze-builder-enumerator
PORTVERSION=	0.2.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enumeratees for the incremental conversion of builders to bytestrings

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder>=0.2.1.4 enumerator>=0.4.3.1 \
		streaming-commons>=0.1.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
