# $FreeBSD$

PORTNAME=	exceptions
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible optionally-pure exceptions

USE_CABAL=	mtl>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
