# $FreeBSD$

PORTNAME=	exceptions
PORTVERSION=	0.6.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible optionally-pure exceptions

USE_CABAL=	mtl>=2.0 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
