# $FreeBSD$

PORTNAME=	vty
PORTVERSION=	4.7.0.14
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple terminal access library

LICENSE=	BSD

USE_CABAL=	mtl>=1.1.1.0 parallel>=2.2 parsec>=2 terminfo>=0.3 \
		utf8-string>=0.3 vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
