# $FreeBSD: head/devel/hs-easy-file/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	easy-file
PORTVERSION=	0.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform File handling

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
