# $FreeBSD$

PORTNAME=	control-monad-loop
PORTVERSION=	0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple monad transformer for imperative-style loops

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers transformers-base

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
