# $FreeBSD: head/textproc/hs-attoparsec/Makefile 349475 2014-03-29 00:52:54Z pgj $

PORTNAME=	attoparsec
PORTVERSION=	0.11.2.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast combinator parsing for bytestrings

LICENSE=	BSD

USE_CABAL=	text>=1.1.1.3 scientific>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
