# $FreeBSD$

PORTNAME=	attoparsec
PORTVERSION=	0.11.2.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast combinator parsing for bytestrings

LICENSE=	BSD

USE_CABAL=	text>=0.11.3.1 scientific>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
