# New ports collection makefile for: hs-attoparsec
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-attoparsec/Makefile,v 1.1 2011/08/13 18:42:01 pgj Exp $
#

PORTNAME=	attoparsec
PORTVERSION=	0.10.0.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast combinator parsing for bytestrings

LICENSE=	BSD

USE_CABAL=	deepseq text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
