# New ports collection makefile for:	hs-data-object
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-data-object/Makefile,v 1.1 2012/02/18 16:53:33 pgj Exp $
#

PORTNAME=	data-object
PORTVERSION=	0.3.1.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Represent hierarchical structures, called objects in JSON

LICENSE=	BSD

USE_CABAL=	failure>=0.1.0 text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
