# New ports collection makefile for: hs-random
# Date created:        May 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	random
PORTVERSION=	1.0.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for random

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
