# $FreeBSD$

PORTNAME=	filepath
PORTVERSION=	1.3.0.2
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Library for manipulating FilePaths in a cross platform way

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
