# $FreeBSD: head/security/hs-monadcryptorandom/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	monadcryptorandom
PORTVERSION=	0.6.1
PORTREVISION=	2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad for using CryptoRandomGen

LICENSE=	BSD3CLAUSE

USE_CABAL=	crypto-api>=0.2 mtl>=2.0 tagged>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
