# New ports collection makefile for: hs-hxt-unicode
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-hxt-unicode/Makefile,v 1.1 2011/05/08 18:40:59 pgj Exp $
#

PORTNAME=	hxt-unicode
PORTVERSION=	9.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode functions for utf8, iso-latin-* and other encodings

CABAL_SETUP=	Setup.hs

USE_CABAL=	hxt-charproperties>=9

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
