# New ports collection makefile for: hs-hxt-unicode
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-hxt-unicode/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	hxt-unicode
PORTVERSION=	9.0.2
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode functions for UTF-8, iso-latin-* and other encodings

CABAL_SETUP=	Setup.hs

USE_CABAL=	hxt-charproperties>=9

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
