# New ports collection makefile for: hs-hxt-unicode
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-hxt-unicode/Makefile,v 1.3 2012/02/13 05:35:36 pgj Exp $
#

PORTNAME=	hxt-unicode
PORTVERSION=	9.0.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode functions for utf8, iso-latin-* and other encodings

CABAL_SETUP=	Setup.hs

USE_CABAL=	hxt-charproperties>=9

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
