# $FreeBSD: head/devel/hs-js-flot/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	js-flot
PORTVERSION=	0.8.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified flot code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
