# $FreeBSD$

PORTNAME=	classy-prelude-conduit
PORTVERSION=	0.7.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Conduit instances for classy-prelude

LICENSE=	MIT

USE_CABAL=	classy-prelude>=0.7 conduit>=0.5.4.1 monad-control \
		resourcet system-fileio transformers void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
