# $FreeBSD$

PORTNAME=	classy-prelude-conduit
PORTVERSION=	0.9.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Conduit instances for classy-prelude

LICENSE=	MIT

USE_CABAL=	classy-prelude>=0.9.2 conduit>=1.0 conduit-combinators>=0.2.4 \
		monad-control resourcet system-fileio void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
