# $FreeBSD: head/devel/hs-geniplate-mirror/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	geniplate-mirror
PORTVERSION=	0.7.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to generate Uniplate-like functions

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
