# $FreeBSD$

PORTNAME=	data-lens-light
PORTVERSION=	0.1.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple lenses, minimum dependencies

LICENSE=	MIT

USE_CABAL=	mtl>=2.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
