# $FreeBSD: head/devel/hs-ConfigFile/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ConfigFile
PORTVERSION=	1.1.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Configuration file reading and writing

LICENSE=	BSD3CLAUSE

USE_CABAL=	MissingH>=1.0.0 mtl parsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
