# New ports collection makefile for: hs-hxt-regex-xmlschema
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-hxt-regex-xmlschema/Makefile,v 1.2 2011/05/26 00:51:10 ashish Exp $
#

PORTNAME=	hxt-regex-xmlschema
PORTVERSION=	9.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A regular expression library for W3C XML Schema regular expressions

CABAL_SETUP=	Setup.hs
USE_CABAL=	hxt-charproperties>=9 parsec>=2.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
