# $FreeBSD: head/devel/hs-haddock-api/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	haddock-api
PORTVERSION=	2.16.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation-generation tool for Haskell libraries

LICENSE=	BSD3CLAUSE

USE_CABAL=	ghc-paths haddock-library>=1.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
