# $FreeBSD: head/graphics/hs-dia-base/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	dia-base
PORTVERSION=	0.1.1.3
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	EDSL for teaching Haskell with diagrams - data types

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
