# $FreeBSD: head/devel/hs-quickcheck-io/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	quickcheck-io
PORTVERSION=	0.1.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use HUnit assertions as QuickCheck properties

LICENSE=	MIT

USE_CABAL=	HUnit>=1.2.5 QuickCheck>=2.5.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
