# $FreeBSD: head/devel/hs-dlist-instances/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	dlist-instances
PORTVERSION=	0.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Difference lists instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist semigroups

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
