# $FreeBSD: head/textproc/hs-cmark/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cmark
PORTVERSION=	0.4.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast, accurate CommonMark (Markdown) parser and renderer

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
