# New ports collection makefile for: hs-strict
# Date created:        May 14, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-strict/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	strict
PORTVERSION=	0.3.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Strict data types and String IO

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
