# $FreeBSD: head/devel/hs-strict/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	strict
PORTVERSION=	0.3.2
PORTREVISION=	12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Strict data types and String IO

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
