# New ports collection makefile for: hs-strict
# Date created:        May 14, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-strict/Makefile,v 1.2 2012/06/03 20:52:17 pgj Exp $
#

PORTNAME=	strict
PORTVERSION=	0.3.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Strict data types and String IO

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
