# $FreeBSD: head/devel/hs-bytestring-show/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bytestring-show
PORTVERSION=	0.3.5.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient conversion of values into readable byte strings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
