# New ports collection makefile for: hs-bytestring-show
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	bytestring-show
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient conversion of values into readable byte strings

LICENSE=	BSD

USE_CABAL=	binary

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
