# New ports collection makefile for: hs-base-unicode-symbols
# Date created:        September 24, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-base-unicode-symbols/Makefile,v 1.1 2012/02/17 15:44:09 pgj Exp $
#

PORTNAME=	base-unicode-symbols
PORTVERSION=	0.2.2.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode alternatives for common functions and operators

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
