# $FreeBSD: head/devel/hs-base-unicode-symbols/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	base-unicode-symbols
PORTVERSION=	0.2.2.4
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode alternatives for common functions and operators

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
