# $FreeBSD: head/www/hs-happstack/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	happstack
PORTVERSION=	7.0.2
PORTREVISION=	2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The haskell application server stack + code generation

LICENSE=	BSD3CLAUSE

USE_CABAL=	happstack-server>=7.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
