# $FreeBSD$

PORTNAME=	pretty-show
PORTVERSION=	1.6.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Tools for derived `Show` instances and generic inspection of values

LICENSE=	BSD

USE_CABAL=	haskell-lexer>=1

EXECUTABLE=	ppsh

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
