# $FreeBSD$

PORTNAME=	pretty-show
PORTVERSION=	1.6.8.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Tools for derived `Show` instances and generic inspection of values

LICENSE=	MIT

USE_CABAL=	haskell-lexer>=1
USE_HAPPY=	yes

EXECUTABLE=	ppsh

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
