# New ports collection makefile for: hs-monad-par-extras
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	monad-par-extras
PORTVERSION=	0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinators and extra features for Par monads

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	abstract-par cereal deepseq mtl transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
