# $FreeBSD$

PORTNAME=	dyre
PORTVERSION=	0.8.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Dynamic reconfiguration in Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	ghc-paths io-storage xdg-basedir

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
