# $FreeBSD$

PORTNAME=	dyre
PORTVERSION=	0.8.11
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Dynamic reconfiguration in Haskell

LICENSE=	BSD

USE_CABAL=	executable-path ghc-paths io-storage xdg-basedir

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
