# New ports collection makefile for:	hs-byteorder
# Date created:		December 30, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-byteorder/Makefile,v 1.2 2012/06/03 20:52:11 pgj Exp $
#

PORTNAME=	byteorder
PORTVERSION=	1.0.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Exposes the native endianness or byte ordering of the system

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
