# New ports collection makefile for:	hs-byteorder
# Date created:		December 30, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-byteorder/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	byteorder
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Exposes the native endianness or byte ordering of the system

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
