# $FreeBSD: head/devel/hs-byteorder/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	byteorder
PORTVERSION=	1.0.4
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Exposes the native endianness or byte ordering of the system

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
