# New ports collection makefile for: hs-bits-atomic
# Date created:        May 12, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-bits-atomic/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	bits-atomic
PORTVERSION=	0.1.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Atomic bit operations on memory locations

LICENSE=	BSD
FILE_LICENSE=	License.txt

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
