# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/print/hs-hscolour/Makefile 409206 2016-02-19 20:49:11Z pgj $

PORTNAME=	hscolour
PORTVERSION=	${HSCOLOUR_VERSION}
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Colourise Haskell code

LICENSE=	GPLv2

EXECUTABLE=	HsColour

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
