# New ports collection makefile for:	hs-zlib-bindings
# Date created:				October 18, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD: ports/archivers/hs-zlib-bindings/Makefile,v 1.1 2012/02/13 02:02:34 pgj Exp $

PORTNAME=	zlib-bindings
PORTVERSION=	0.0.3.1
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level bindings to the zlib package

LICENSE=	BSD

USE_CABAL=	zlib>=0.5.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
