# New ports collection makefile for:	hs-zlib-bindings
# Date created:				October 18, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD: head/archivers/hs-zlib-bindings/Makefile 300895 2012-07-14 12:56:14Z beat $

PORTNAME=	zlib-bindings
PORTVERSION=	0.1.0.1
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level bindings to the zlib package

LICENSE=	BSD

USE_CABAL=	zlib>=0.5.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
