# $FreeBSD: head/archivers/hs-zlib-bindings/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	zlib-bindings
PORTVERSION=	0.1.1.5
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level bindings to the zlib package

LICENSE=	BSD3CLAUSE

USE_CABAL=	zlib>=0.5.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
