# $FreeBSD: head/textproc/hs-regex-compat/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	regex-compat
PORTVERSION=	0.95.1
PORTREVISION=	12
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

LICENSE=	BSD3CLAUSE

USE_CABAL=	regex-base>=0.93 regex-posix>=0.95.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
