# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/lang/hs-brainfuck/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	brainfuck
PORTVERSION=	0.1.0.2
CATEGORIES=	lang haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Brainfuck interpreter

LICENSE=	GPLv2

USE_CABAL=	mtl

EXECUTABLE=	bf

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
