# $FreeBSD$

PORTNAME=	hscurses
PORTVERSION=	1.4.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	NCurses bindings for Haskell

LICENSE=	LGPL21

USE_CABAL=	exceptions mtl old-locale>=1.0 old-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
