# New ports collection makefile for: hs-cookie
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-cookie/Makefile,v 1.1 2012/02/18 16:51:17 pgj Exp $
#

PORTNAME=	cookie
PORTVERSION=	0.3.0.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP cookie parsing and rendering

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2.1 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
