# New ports collection makefile for: hs-cookie
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-cookie/Makefile,v 1.2 2012/06/03 22:37:39 pgj Exp $
#

PORTNAME=	cookie
PORTVERSION=	0.4.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP cookie parsing and rendering

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2.1 data-default text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
