# New ports collection makefile for: hs-utf8-light
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-utf8-light/Makefile,v 1.1 2012/06/24 10:04:39 pgj Exp $
#

PORTNAME=	utf8-light
PORTVERSION=	0.4.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
