# $FreeBSD: head/devel/hs-utf8-light/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	utf8-light
PORTVERSION=	0.4.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unicode

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
