# New ports collection makefile for: hs-test-framework-quickcheck2
# Date created:        May 21, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-test-framework-quickcheck2/Makefile,v 1.7 2012/02/13 04:48:47 pgj Exp $
#

PORTNAME=	test-framework-quickcheck2
PORTVERSION=	0.2.12.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	QuickCheck2 support for the test-framework package

LICENSE=	BSD

USE_CABAL=	QuickCheck>=2.4 test-framework>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
