# $FreeBSD: head/security/hs-crypto-numbers/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-numbers
PORTVERSION=	0.2.7
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cryptographic numbers: functions and algorithms

LICENSE=	BSD3CLAUSE

USE_CABAL=	crypto-random>=0.0.0 vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
