# $FreeBSD: head/devel/hs-asn1-data/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	asn1-data
PORTVERSION=	0.7.1
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	ASN1 data reader and writer in RAW, BER, and DER forms

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal mtl text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
