# New ports collection makefile for: hs-temporary
# Date created:        February 6, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-temporary/Makefile,v 1.1 2012/06/03 19:13:46 pgj Exp $
#

PORTNAME=	temporary
PORTVERSION=	1.1.2.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable temporary file and directory support for Windows and Unix

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
