# $FreeBSD$

PORTNAME=	temporary
PORTVERSION=	1.2.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable temporary file and directory support for Windows and Unix

LICENSE=	BSD

USE_CABAL=	exceptions>=0.1.1 transformers>=0.2.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
