# New ports collection makefile for: hs-temporary
# Date created:        February 6, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-temporary/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	temporary
PORTVERSION=	1.1.2.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable temporary file and directory support for Windows and Unix

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
