# New ports collection makefile for: hs-SafeSemaphore
# Date created:        June 27, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	SafeSemaphore
PORTVERSION=	0.9.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Much safer replacement for QSemN, QSem, and SampleVar

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	stm

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
