# $FreeBSD: head/devel/hs-SafeSemaphore/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	SafeSemaphore
PORTVERSION=	0.10.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Much safer replacement for QSemN, QSem, and SampleVar

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
