# New ports collection makefile for: hs-unix-compat
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-unix-compat/Makefile,v 1.7 2011/08/13 21:13:03 pgj Exp $
#

PORTNAME=	unix-compat
PORTVERSION=	0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Portable POSIX-compatibility layer for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
