# $FreeBSD: head/devel/hs-bytestring-mmap/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bytestring-mmap
PORTVERSION=	0.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mmap support for strict ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
