# $FreeBSD$

PORTNAME=	shakespeare-js
PORTVERSION=	1.0.0.5
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Stick your Haskell variables into JavaScript at compile time

LICENSE=	MIT

USE_CABAL=	shakespeare>=1.0.0.3 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
