# New ports collection makefile for: hs-shakespeare-js
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-shakespeare-js/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	shakespeare-js
PORTVERSION=	1.0.0.3
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Stick your Haskell variables into JavaScript at compile time

LICENSE=	MIT

USE_CABAL=	shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
