# New ports collection makefile for: hs-shakespeare-js
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare-js/Makefile,v 1.1 2012/02/18 17:32:38 pgj Exp $
#

PORTNAME=	shakespeare-js
PORTVERSION=	1.0.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Stick your Haskell variables into JavaScript at compile time

LICENSE=	BSD

USE_CABAL=	shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
