# $FreeBSD$

PORTNAME=	fast-logger
PORTVERSION=	2.1.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast logging system

LICENSE=	BSD

USE_CABAL=	blaze-builder text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
