# New ports collection makefile for: hs-fast-logger
# Date created:        December 30, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-fast-logger/Makefile,v 1.2 2012/06/03 20:52:12 pgj Exp $
#

PORTNAME=	fast-logger
PORTVERSION=	0.0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A fast logging system

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	blaze-builder

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
