# New ports collection makefile for: hs-directory-tree
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-directory-tree/Makefile 301891 2012-08-03 02:54:12Z pgj $
#

PORTNAME=	directory-tree
PORTVERSION=	0.10.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple directory-like tree datatype, with useful IO functions

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
