# $FreeBSD: head/devel/hs-directory-tree/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	directory-tree
PORTVERSION=	0.12.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple directory-like tree datatype, with useful IO functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
