# $FreeBSD$

PORTNAME=	shelly-extra
PORTVERSION=	0.2.2.1
CATEGORIES=	shells haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	shelly features that require extra dependencies

LICENSE=	BSD

USE_CABAL=	SafeSemaphore shelly>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
