# $FreeBSD$

PORTNAME=	shelly-extra
PORTVERSION=	0.2.3.1
CATEGORIES=	shells haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	shelly features that require extra dependencies

LICENSE=	BSD3CLAUSE

USE_CABAL=	SafeSemaphore>=0.7 shelly>=0.13

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
