# $FreeBSD$

PORTNAME=	binary-shared
PORTVERSION=	0.8.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Sharing for the binary package

LICENSE=	GPLv2

USE_CABAL=	mtl>=1.1.0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
