# New ports collection makefile for: hs-syb-with-class-instances-text
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-syb-with-class-instances-text/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	syb-with-class-instances-text
PORTVERSION=	0.0.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class Text instance

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	syb-with-class text>=0.7.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
