# $FreeBSD$

PORTNAME=	monads-tf
PORTVERSION=	0.1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad classes, using type families

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers>=0.2.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
