# New ports collection makefile for: hs-FileManip
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-filemanip/Makefile,v 1.12 2012/06/03 20:52:12 pgj Exp $
#

PORTNAME=	filemanip
PORTVERSION=	0.3.5.2
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Expressive file and directory manipulation for Haskell

LICENSE=	BSD

USE_CABAL=	mtl unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
