# New ports collection makefile for: hs-FileManip
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-FileManip/Makefile,v 1.4 2010/07/30 08:49:50 pgj Exp $
#

PORTNAME=	filemanip
PORTVERSION=	0.3.5.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Expressive file and directory manipulation for Haskell

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_HACKAGE=	mtl unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
