# New ports collection makefile for: hs-FileManip
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-filemanip/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	filemanip
PORTVERSION=	0.3.5.2
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Expressive file and directory manipulation for Haskell

LICENSE=	BSD

USE_CABAL=	mtl unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
