# $FreeBSD$

PORTNAME=	parallel-io
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinators for executing IO actions in parallel on a thread pool

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions>0.1.0.1 random>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
