# $FreeBSD$

PORTNAME=	parallel-io
PORTVERSION=	0.3.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinators for executing IO actions in parallel on a thread pool

LICENSE=	BSD

USE_CABAL=	random>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
