# $FreeBSD: head/devel/hs-data-default-instances-old-locale/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-default-instances-old-locale
PORTVERSION=	0.0.1
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in old-locale

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
