# New ports collection makefile for: hs-scgi
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/www/hs-scgi/Makefile,v 1.4 2010/06/08 12:04:16 pgj Exp $
#

# deprecated: use wai

PORTNAME=	scgi
PORTVERSION=	0.3.3
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for writing SCGI programs

LICENSE=	BSD

USE_CABAL=	cgi network>=2.2.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
