# $FreeBSD: head/textproc/hs-blaze-markup/Makefile 349475 2014-03-29 00:52:54Z pgj $

PORTNAME=	blaze-markup
PORTVERSION=	0.6.1.0
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Blazingly fast markup combinator library

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2 text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
