# $FreeBSD: head/devel/hs-data-hash/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-hash
PORTVERSION=	0.2.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinators for building fast hashing functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
