# $FreeBSD$

PORTNAME=	dynamic-state
PORTVERSION=	0.2.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Optionally serializable dynamic state keyed by type

LICENSE=	GPLv2

USE_CABAL=	hashable unordered-containers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
