# New ports collection makefile for: hs-bloomfilter
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-bloomfilter/Makefile 301888 2012-08-03 02:51:57Z pgj $
#

PORTNAME=	bloomfilter
PORTVERSION=	1.2.6.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure and impure Bloom Filter implementations

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
