# $FreeBSD: head/devel/hs-bloomfilter/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bloomfilter
PORTVERSION=	2.0.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure and impure Bloom Filter implementations

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
