# New ports collection makefile for: hs-bloomfilter
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-bloomfilter/Makefile,v 1.1 2012/06/03 19:01:29 pgj Exp $
#

PORTNAME=	bloomfilter
PORTVERSION=	1.2.6.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure and impure Bloom Filter implementations

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
