# $FreeBSD: head/devel/hs-hashtables/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hashtables
PORTVERSION=	1.2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mutable hash tables in the ST monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.1 primitive vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
