# New ports collection makefile for: hs-syb
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-syb/Makefile,v 1.2 2011/05/26 00:51:02 ashish Exp $
#

PORTNAME=	syb
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
