# New ports collection makefile for: hs-syb
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-syb/Makefile,v 1.3 2012/02/13 04:45:33 pgj Exp $
#

PORTNAME=	syb
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
