# New ports collection makefile for: hs-shakespeare-text
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare-text/Makefile,v 1.1 2012/02/18 17:34:41 pgj Exp $
#

PORTNAME=	shakespeare-text
PORTVERSION=	1.0.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interpolation with quasi-quotation: put variables strings

LICENSE=	BSD

USE_CABAL=	shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
