# New ports collection makefile for: hs-xhtml-combinators
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	xhtml-combinators
PORTVERSION=	0.2.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast and easy to use XHTML combinators

LICENSE=	BSD

USE_CABAL=	text>=0.7 transformers>=0.2 xml>=1.3.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
