# $FreeBSD$

PORTNAME=	xhtml-combinators
PORTVERSION=	0.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast and easy to use XHTML combinators

LICENSE=	BSD3CLAUSE

USE_CABAL=	random text>=0.7 transformers>=0.2 xml>=1.3.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
