# $FreeBSD: head/net/hs-iproute/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	iproute
PORTVERSION=	1.5.0
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	IP Routing Table

LICENSE=	BSD3CLAUSE

USE_CABAL=	appar byteorder network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
