# $FreeBSD: head/devel/hs-extra/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	extra
PORTVERSION=	1.4.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extra functions

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
