# New ports collection makefile for: hs-blaze-textual
# Date created:        May 25, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-blaze-textual/Makefile,v 1.3 2012/06/03 20:52:11 pgj Exp $
#

PORTNAME=	blaze-textual
PORTVERSION=	0.2.0.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A library for efficiently rendering Haskell datatypes to bytestrings

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2.1.4 text>=0.11.0.2 vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
