# New ports collection makefile for: hs-ghc-syb-utils
# Date created:        June 12, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	ghc-syb-utils
PORTVERSION=	0.2.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate utilities for the GHC API

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	syb>=0.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
