# $FreeBSD$

PORTNAME=	ghc-syb-utils
PORTVERSION=	0.2.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate utilities for the GHC API

LICENSE=	BSD

USE_CABAL=	syb>=0.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
