# $FreeBSD$

PORTNAME=	ghcjs-codemirror
PORTVERSION=	0.0.0.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Installs CodeMirror JavaScript files

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
