# $FreeBSD: head/textproc/hs-parsec/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	parsec
PORTVERSION=	3.1.9
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monadic parser combinators

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl text>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
