# $FreeBSD: head/textproc/hs-parsec/Makefile 349475 2014-03-29 00:52:54Z pgj $

PORTNAME=	parsec
PORTVERSION=	3.1.5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monadic parser combinators

LICENSE=	BSD

USE_CABAL=	mtl text>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
