# New ports collection makefile for:	hs-entropy
# Date created:		July 13, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: head/security/hs-entropy/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	entropy
PORTVERSION=	0.2.1
PORTREVISION=	1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A platform-independent entropy source

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
