# $FreeBSD$

PORTNAME=	entropy
PORTVERSION=	0.2.2.1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Platform-independent entropy source

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
