# New ports collection makefile for:	hs-entropy
# Date created:		July 13, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/security/hs-entropy/Makefile,v 1.1 2012/02/13 02:49:00 pgj Exp $
#

PORTNAME=	entropy
PORTVERSION=	0.2.1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A platform-independent entropy source

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
