# $FreeBSD$

PORTNAME=	unbounded-delays
PORTVERSION=	0.1.0.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unbounded thread delays and timeouts

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
