# $FreeBSD: head/devel/hs-scientific/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	scientific
PORTVERSION=	0.3.3.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Numbers represented using scientific notation

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.1.2 text>=0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
