# New ports collection makefile for: hs-shelly
# Date created:        June 27, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	shelly
PORTVERSION=	0.13.1
CATEGORIES=	shells haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	shell-like (systems) programming in Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	mtl system-fileio system-filepath text unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
