# $FreeBSD$

PORTNAME=	shelly
PORTVERSION=	0.15.2
CATEGORIES=	shells haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Shell-like (systems) programming in Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	mtl system-fileio system-filepath text unix-compat

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
