# $FreeBSD$

MAINTAINER=	ports@FreeBSD.org
USE_GCC=	yes

MASTERDIR=	${.CURDIR}/../../devel/llvm33

.include "${MASTERDIR}/Makefile"

CONFLICTS=	llvm${LLVM_SUFFIX}-*
PKGNAMESUFFIX:=	${LLVM_SUFFIX}-gcc
