# $FreeBSD: head/devel/hs-tf-random/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	tf-random
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	High-quality splittable pseudorandom number generator

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive>=0.3 random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
