# $FreeBSD$

PORTNAME=	groom
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pretty printing for well-behaved Show instances

USE_CABAL=	haskell-src-exts>=1.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
