# $FreeBSD$

PORTNAME=	tasty
PORTVERSION=	0.10.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Modern and extensible testing framework

LICENSE=	MIT

USE_CABAL=	ansi-terminal>=0.6.2 async>=2.0 mtl \
		optparse-applicative>=0.11 regex-tdfa-rc>=1.1.8.2 stm>=2.3 \
		tagged>=0.5 unbounded-delays>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
