# Created by: obraun@FreeBSD.org
# $FreeBSD: head/devel/hs-cpphs/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cpphs
PORTVERSION=	1.19
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Liberalised re-implementation of cpp, the C pre-processor

LICENSE=	LGPL21

USE_CABAL=	old-locale old-time polyparse>=1.9

EXECUTABLE=	cpphs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
