# New ports collection makefile for:	cpphs
# Date created:		14 June 2004
# Whom:			obraun@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-cpphs/Makefile,v 1.25 2012/02/13 12:58:22 pgj Exp $
#

PORTNAME=	cpphs
PORTVERSION=	1.13.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simplified re-implementation of cpp in Haskell

LICENSE=	LGPL21
FILE_LICENSE=	LICENCE-LGPL

CABAL_SETUP=	Setup.hs

EXECUTABLE=	cpphs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
