# New ports collection makefile for: hs-IfElse
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-IfElse/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	IfElse
PORTVERSION=	0.85
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Anaphoric and miscellaneous useful control-flow

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
