# New ports collection makefile for: hs-IfElse
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-IfElse/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	IfElse
PORTVERSION=	0.85
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Anaphoric and miscellaneous useful control-flow

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
