# $FreeBSD: head/devel/hs-IfElse/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	IfElse
PORTVERSION=	0.85
PORTREVISION=	11
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Anaphoric and miscellaneous useful control-flow

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
