# $FreeBSD: head/textproc/hs-attoparsec-enumerator/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	attoparsec-enumerator
PORTVERSION=	0.3.4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pass input from an enumerator to an Attoparsec parser

LICENSE=	MIT

USE_CABAL=	attoparsec>=0.10 enumerator>=0.4 text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
