# $FreeBSD: head/www/hs-multipart/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	multipart
PORTVERSION=	0.1.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP multipart split out of the cgi package

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
