# $FreeBSD: head/devel/hs-errors/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	errors
PORTVERSION=	2.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simplified error-handling

LICENSE=	BSD3CLAUSE

USE_CABAL=	safe>=0.3.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
