# $FreeBSD$

PORTNAME=	errors
PORTVERSION=	1.4.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simplified error-handling

LICENSE=	BSD3CLAUSE

USE_CABAL=	either>=3.1 safe>=0.3.3 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
