# $FreeBSD$

PORTNAME=	sourcemap
PORTVERSION=	0.1.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Implementation of source maps as proposed by Google and Mozilla

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson attoparsec text unordered-containers utf8-string

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
