# $FreeBSD: head/devel/hs-enumerator/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	enumerator
PORTVERSION=	0.4.20
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reliable, high-performance processing with left-fold enumerators

LICENSE=	MIT

USE_CABAL=	text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
