# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-MonadCatchIO-mtl/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	MonadCatchIO-mtl
PORTVERSION=	0.3.1.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer version of the Control.Exception module

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions MonadCatchIO-transformers>=0.3.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
