# New ports collection makefile for: hs-MonadCatchIO-mtl
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-MonadCatchIO-mtl/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	MonadCatchIO-mtl
PORTVERSION=	0.3.0.4
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer version of the Control.Exception Haskell module

LICENSE=	BSD

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
