# New ports collection makefile for: hs-MonadCatchIO-mtl
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-MonadCatchIO-mtl/Makefile,v 1.9 2012/02/13 03:49:20 pgj Exp $
#

PORTNAME=	MonadCatchIO-mtl
PORTVERSION=	0.3.0.4
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer version of the Control.Exception Haskell module

LICENSE=	BSD

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
