# New ports collection makefile for:	hs-polyparse-ghc
# Date created:				January 23, 2009
# Whom:					Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/textproc/hs-polyparse/Makefile,v 1.9 2011/05/26 00:51:11 ashish Exp $
#

PORTNAME=	polyparse
PORTVERSION=	1.6
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Alternative parser combinator libraries for Haskell

LICENSE=	LGPL21
FILE_LICENSE=	COPYRIGHT

CABAL_SETUP=	Setup.hs
USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
