# New ports collection makefile for:	hs-polyparse-ghc
# Date created:				January 23, 2009
# Whom:					Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/textproc/hs-polyparse/Makefile,v 1.7 2010/05/24 21:52:37 pgj Exp $
#

PORTNAME=	polyparse
PORTVERSION=	1.5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Alternative parser combinator libraries for Haskell

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
