# $FreeBSD$

PORTNAME=	contravariant
PORTVERSION=	0.6
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Contravariant functors

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers-compat>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
