# $FreeBSD$

PORTNAME=	contravariant
PORTVERSION=	0.4.4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Contravariant functors

LICENSE=	BSD3CLAUSE

USE_CABAL=	tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
