# $FreeBSD: head/devel/hs-HUnit/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	HUnit
PORTVERSION=	1.2.5.2
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unit testing framework for Haskell

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
