# New ports collection makefile for:	hs-HUnit
# Date created:		2010-08-10
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-HUnit/Makefile,v 1.3 2012/02/13 04:09:16 pgj Exp $
#

PORTNAME=	HUnit
PORTVERSION=	1.2.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unit testing framework for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
