# New ports collection makefile for: hs-QuickCheck-docs
# Date created:        May 11, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$

PORTNAME=	QuickCheck
PORTVERSION=	2.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for QuickCheck

LICENSE=	BSD

USE_CABAL=	random

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
