# New ports collection makefile for: hs-yesod-routes
# Date created:        April 8, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-yesod-routes/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	yesod-routes
PORTVERSION=	1.0.1.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient routing for Yesod

LICENSE=	MIT

USE_CABAL=	path-pieces>=0.1 text>=0.5 vector>=0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
