--- ./formats/haskell2/HaskellTop.hs.orig	2010-09-15 16:26:38.000000000 +0200
+++ ./formats/haskell2/HaskellTop.hs	2012-05-12 22:21:11.000000000 +0200
@@ -42,7 +42,6 @@
 
 import Char
 import Data.Maybe (fromMaybe,maybe)
-import System
 import Monad(when)
 
 -- naming conventions
@@ -235,8 +234,8 @@
 	        ["-- automatically generated by BNF Converter",
 		 "module Main where\n",
 	         "",
-	         "import IO ( stdin, hGetContents )",
-	         "import System ( getArgs, getProgName )",
+	         "import System.IO ( stdin, hGetContents )",
+	         "import System.Environment ( getArgs, getProgName )",
 		 "",
 		 "import " ++ alexFileM     opts,
 		 "import " ++ happyFileM    opts,
