# $FreeBSD$

PORTNAME=	testing-feat
PORTVERSION=	0.4.0.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Functional Enumeration of Algebraic Types

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1 QuickCheck>2 tagshare

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
