# New ports collection makefile for: hs-regex-pcre-builtin
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-regex-pcre-builtin/Makefile,v 1.3 2012/02/13 03:49:31 pgj Exp $
#

PORTNAME=	regex-pcre-builtin
PORTVERSION=	0.94.2.1.7.7
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	regex-base>=0.93

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
