# $FreeBSD: head/devel/hs-asn1-encoding/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	asn1-encoding
PORTVERSION=	0.9.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	ASN1 data reader and writer in RAW, BER and DER forms

LICENSE=	BSD3CLAUSE

USE_CABAL=	asn1-types>=0.3.0 hourglass>=0.2.6 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
