# $FreeBSD: head/devel/hs-newtype/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	newtype
PORTVERSION=	0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclass and set of functions for working with newtypes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
