# $FreeBSD: head/devel/hs-edit-distance/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	edit-distance
PORTVERSION=	0.2.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Levenshtein and restricted Damerau-Levenshtein edit distances

LICENSE=	BSD3CLAUSE

USE_CABAL=	random>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
