# New ports collection makefile for: hs-edit-distance
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-edit-distance/Makefile,v 1.1 2012/06/03 19:04:00 pgj Exp $
#

PORTNAME=	edit-distance
PORTVERSION=	0.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Levenshtein and restricted Damerau-Levenshtein edit distances

LICENSE=	BSD

USE_CABAL=	random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
