# $FreeBSD$

PORTNAME=	reducers
PORTVERSION=	3.10.1.1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Semigroups, specialized containers and a general map/reduce framework

LICENSE=	BSD

USE_CABAL=	comonad>=4 fingertree>=0.1 hashable>=1.1.2.1 keys>=3.10 \
		pointed>=4 semigroupoids>=4 semigroups>=0.8.3.1 \
		text>=0.11.1.5 transformers>=0.2 unordered-containers>=0.1.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
