# New ports collection makefile for: hs-syb-with-class
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-syb-with-class/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	syb-with-class
PORTVERSION=	0.6.1.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
