# $FreeBSD: head/devel/hs-syb-with-class/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	syb-with-class
PORTVERSION=	0.6.1.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
