# New ports collection makefile for: hs-syb-with-class
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-syb-with-class/Makefile,v 1.2 2012/06/03 20:52:17 pgj Exp $
#

PORTNAME=	syb-with-class
PORTVERSION=	0.6.1.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Scrap Your Boilerplate With Class

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
