# $FreeBSD: head/x11-toolkits/hs-OpenGLRaw/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	OpenGLRaw
PORTVERSION=	2.5.1.0
CATEGORIES=	x11-toolkits haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Raw binding for the OpenGL graphics system

LICENSE=	BSD3CLAUSE

USE_GL=		gl glut

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
