# New ports collection makefile for: hs-OpenGLRaw-ghc
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/x11-toolkits/hs-OpenGLRaw/Makefile,v 1.5 2010/05/26 11:18:46 jacula Exp $
#

PORTNAME=	OpenGLRaw
PORTVERSION=	1.1.0.1
PORTREVISION=	1
CATEGORIES=	x11-toolkits haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A raw Haskell binding for the OpenGL graphics system

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_GL=	gl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
