# $FreeBSD$

PORTNAME=	distributive
PORTVERSION=	0.3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 distributive functors -- Dual to Traversable

LICENSE=	BSD

USE_CABAL=	transformers>=0.2 transformers-compat>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
