# $FreeBSD: head/math/hs-distributive/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	distributive
PORTVERSION=	0.4.4
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Distributive functors -- Dual to Traversable

LICENSE=	BSD3CLAUSE

USE_CABAL=	tagged>=0.7 transformers-compat>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
