# $FreeBSD: head/sysutils/hs-ekg-core/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ekg-core
PORTVERSION=	0.1.1.0
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Tracking of system metrics

LICENSE=	BSD3CLAUSE

USE_CABAL=	text unordered-containers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
