# New ports collection makefile for: hs-double-conversion
# Date created:        July 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-double-conversion/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	double-conversion
PORTVERSION=	0.2.0.4
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast conversion between double-precision floating point and text

LICENSE=	BSD

USE_CABAL=	text>=0.11.0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
