# New ports collection makefile for: hs-DeepArrow
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-DeepArrow/Makefile,v 1.3 2010/05/26 11:18:34 jacula Exp $
#

PORTNAME=	DeepArrow
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell arrows for deep application

LICENSE=	BSD

USE_CABAL=	haskell-src mtl TypeCompose>=0.6.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
