# $FreeBSD: head/devel/hs-hex/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hex
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Convert strings into hexadecimal and back

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
