# $FreeBSD$

PORTNAME=	pqueue
PORTVERSION=	1.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reliable, persistent, fast priority queues

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
