# New ports collection makefile for: hs-utility-ht
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-utility-ht/Makefile,v 1.7 2012/02/13 04:53:36 pgj Exp $
#

PORTNAME=	utility-ht
PORTVERSION=	0.0.7.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various small Haskell helper functions for Lists, Maybes, Tuples, Functions

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
