# New ports collection makefile for: hs-utility-ht
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-utility-ht/Makefile,v 1.8 2012/06/03 22:03:00 pgj Exp $
#

PORTNAME=	utility-ht
PORTVERSION=	0.0.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various small helper functions

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
