# $FreeBSD$

PORTNAME=	setops
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Uniform names (and Unicode operators) for set operations on data structures

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
