# $FreeBSD$

PORTNAME=	xdg-basedir
PORTVERSION=	0.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A basic implementation of the XDG Base Directory specification

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
