# $FreeBSD: head/devel/hs-generic-deriving/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	generic-deriving
PORTVERSION=	1.8.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic programming library for generalised deriving

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
