# New ports collection makefile for: hs-tagged
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-tagged/Makefile,v 1.2 2012/06/03 21:55:43 pgj Exp $
#

PORTNAME=	tagged
PORTVERSION=	0.4.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 phantom types to avoid unsafely passing dummy arguments

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
