# New ports collection makefile for: hs-tagged
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-tagged/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	tagged
PORTVERSION=	0.4.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 phantom types to avoid unsafely passing dummy arguments

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
