# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/www/hs-url/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	url
PORTVERSION=	2.1.3
PORTREVISION=	11
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for working with URLs

LICENSE=	BSD3CLAUSE

USE_CABAL=	utf8-string>=0.3.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
