# $FreeBSD$

PORTNAME=	libffi
PORTVERSION=	0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binding to libffi

LICENSE=	BSD

USES=		pkgconfig

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
