# New ports collection makefile for: hs-html
# Date created:        August 18, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-html/Makefile,v 1.4 2012/06/03 20:52:24 pgj Exp $
#

PORTNAME=	html
PORTVERSION=	1.0.1.2
PORTREVISION=	4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTML combinator library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
