# $FreeBSD$

PORTNAME=	sbv
PORTVERSION=	4.4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	SMT Based Verification: Symbolic Haskell theorem prover using SMT solving

LICENSE=	BSD3CLAUSE

USE_CABAL=	async crackNum data-binary-ieee754 mtl old-time QuickCheck \
		random syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
