# New ports collection makefile for: hs-abstract-par
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-abstract-par/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	abstract-par
PORTVERSION=	0.3.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes generalizing the functionality of the 'monad-par' library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
