# New ports collection makefile for: hs-abstract-par
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-abstract-par/Makefile,v 1.1 2012/06/03 18:57:20 pgj Exp $
#

PORTNAME=	abstract-par
PORTVERSION=	0.3.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes generalizing the functionality of the 'monad-par' library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
