# $FreeBSD: head/devel/hs-hourglass/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hourglass
PORTVERSION=	0.2.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple performant time related library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
