# New ports collection makefile for:	hs-failure
# Date created:		December 25, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-failure/Makefile,v 1.1 2012/02/18 16:14:50 pgj Exp $
#

PORTNAME=	failure
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple type class for success/failure computations

LICENSE=	BSD

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
