# New ports collection makefile for: hs-murmur-hash
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-murmur-hash/Makefile,v 1.1 2011/08/13 21:07:39 pgj Exp $
#

PORTNAME=	murmur-hash
PORTVERSION=	0.1.0.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MurmurHash2 implementation for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
