# New ports collection makefile for: hs-murmur-hash
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-murmur-hash/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	murmur-hash
PORTVERSION=	0.1.0.5
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MurmurHash2 implementation for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
