# New ports collection makefile for: hs-transformers-base
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-transformers-base/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	transformers-base
PORTVERSION=	0.4.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lift computations from the bottom of a transformer stack

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
