# New ports collection makefile for: hs-shakespeare
# Date created:        December 25, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare/Makefile,v 1.2 2012/06/03 22:42:05 pgj Exp $
#

PORTNAME=	shakespeare
PORTVERSION=	1.0.0.2
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A toolkit for making compile-time interpolated templates

LICENSE=	MIT

USE_CABAL=	parsec>=2 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
