# New ports collection makefile for: hs-shakespeare
# Date created:        December 25, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare/Makefile,v 1.1 2012/02/18 17:11:03 pgj Exp $
#

PORTNAME=	shakespeare
PORTVERSION=	0.10.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A toolkit for making compile-time interpolated templates

LICENSE=	BSD

USE_CABAL=	parsec>=2 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
