# New ports collection makefile for: hs-shakespeare
# Date created:        December 25, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-shakespeare/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	shakespeare
PORTVERSION=	1.0.0.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A toolkit for making compile-time interpolated templates

LICENSE=	MIT

USE_CABAL=	parsec>=2 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
