# $FreeBSD: head/devel/hs-hspec-expectations/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hspec-expectations
PORTVERSION=	0.7.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Catchy combinators for HUnit

LICENSE=	MIT

USE_CABAL=	HUnit

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
