# New ports collection makefile for: hs-path-pieces
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-path-pieces/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	path-pieces
PORTVERSION=	0.1.1
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Components of paths

LICENSE=	BSD

USE_CABAL=	text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
