# $FreeBSD: head/www/hs-path-pieces/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	path-pieces
PORTVERSION=	0.2.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Components of paths

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
