# New ports collection makefile for: hs-path-pieces
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-path-pieces/Makefile,v 1.1 2012/02/18 17:18:34 pgj Exp $
#

PORTNAME=	path-pieces
PORTVERSION=	0.1.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Components of paths

LICENSE=	BSD

USE_CABAL=	text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
