# $FreeBSD: head/net/hs-network-uri/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	network-uri
PORTVERSION=	2.6.0.3
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	URI manipulation

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=3.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
