# $FreeBSD$

PORTNAME=	gio
PORTVERSION=	0.12.5.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binding to the GIO

LICENSE=	LGPL21

USES=		pkgconfig
USE_CABAL=	glib>=0.12.5 mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
