# $FreeBSD$

PORTNAME=	haskell-names
PORTVERSION=	0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Name resolution library for Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson data-lens-light haskell-packages>=0.2 \
		haskell-src-exts>=1.15 hse-cpp mtl tagged traverse-with-class \
		type-eq>=0.4.2 uniplate>=1.5.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
