# $FreeBSD: head/devel/hs-ansi-terminal/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ansi-terminal
PORTVERSION=	0.6.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple ANSI terminal support, with Windows compatibility

LICENSE=	BSD3CLAUSE

FLAGS_DISABLE=	Example

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
