# $FreeBSD: head/devel/hs-js-jquery/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	js-jquery
PORTVERSION=	1.11.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Obtain minified jQuery code

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
