# $FreeBSD$

PORTNAME=	derive
PORTVERSION=	2.5.22
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Program and library to derive instances for data types

LICENSE=	BSD3CLAUSE

USE_CABAL=	haskell-src-exts>=1.16 syb uniplate>=1.5

EXECUTABLE=	derive

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
