# $FreeBSD$

PORTNAME=	derive
PORTVERSION=	2.5.12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Program and library to derive instances for data types

LICENSE=	BSD

USE_CABAL=	haskell-src-exts>=1.9 syb transformers>=0.2 uniplate>=1.5

EXECUTABLE=	derive

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
