# New ports collection makefile for:	hs-network
# Date created:		2010-05-14
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/net/hs-network/Makefile,v 1.1 2011/05/08 18:38:27 pgj Exp $
#

PORTNAME=	network
PORTVERSION=	2.3.0.2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Networking-related facilities

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	parsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
