# New ports collection makefile for: hs-semigroups
# Date created:        July 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-semigroups/Makefile,v 1.3 2012/06/03 22:17:20 pgj Exp $
#

PORTNAME=	semigroups
PORTVERSION=	0.8.3.2
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 semigroups

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
