# New ports collection makefile for: hs-semigroups
# Date created:        July 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-semigroups/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	semigroups
PORTVERSION=	0.8.3.2
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 semigroups

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
