# New ports collection makefile for: hs-file-embed
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-file-embed/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	file-embed
PORTVERSION=	0.0.4.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to embed file contents directly

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
