# New ports collection makefile for: hs-file-embed
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-file-embed/Makefile,v 1.1 2012/06/24 09:49:39 pgj Exp $
#

PORTNAME=	file-embed
PORTVERSION=	0.0.4.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to embed file contents directly

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
