# $FreeBSD: head/devel/hs-file-embed/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	file-embed
PORTVERSION=	0.0.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Template Haskell to embed file contents directly

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
