# $FreeBSD: head/devel/hs-deepseq-generics/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	deepseq-generics
PORTVERSION=	0.1.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	GHC.Generics-based Control.DeepSeq.rnf implementation

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
