# $FreeBSD: head/security/hs-crypto-api/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-api
PORTVERSION=	0.13.2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic interface for cryptographic operations

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal>=0.2 entropy tagged>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
