# $FreeBSD: head/devel/hs-prettyclass/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	prettyclass
PORTVERSION=	1.0.0.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pretty printing class similar to Show

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
