# New ports collection makefile for: hs-bsd-sysctl
# Date created:			04 May 2010
# Whom:				Ju Pengfei <jupengfei@gmail.com>
#
# $FreeBSD: head/devel/hs-bsd-sysctl/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
