# New ports collection makefile for: hs-bsd-sysctl
# Date created:			04 May 2010
# Whom:				Ju Pengfei <jupengfei@gmail.com>
#
# $FreeBSD: ports/devel/hs-bsd-sysctl/Makefile,v 1.8 2012/06/03 21:35:41 pgj Exp $
#

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.7
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
