# New ports collection makefile for: hs-bsd-sysctl
# Date created:			04 May 2010
# Whom:				Ju Pengfei <jupengfei@gmail.com>
#
# $FreeBSD: ports/devel/hs-bsd-sysctl/Makefile,v 1.4 2011/05/26 00:50:56 ashish Exp $
#

PORTNAME=	bsd-sysctl
PORTVERSION=	1.0.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	jupengfei@gmail.com
COMMENT=	Access to the BSD sysctl(3) interface

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
