# $FreeBSD$

PORTNAME=	directory
PORTVERSION=	1.2.1.0
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	library for directory handling

LICENSE=	BSD

USE_CABAL=	filepath>=1.3 unix>=2.5.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
