# New ports collection makefile for: hs-NumInstances
# Date created:        September 24, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-NumInstances/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	NumInstances
PORTVERSION=	1.0
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of numeric classes for functions and tuples

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
