# New ports collection makefile for: hs-NumInstances
# Date created:        September 24, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-NumInstances/Makefile,v 1.2 2012/06/03 20:52:20 pgj Exp $
#

PORTNAME=	NumInstances
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of numeric classes for functions and tuples

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
