# $FreeBSD: head/mail/hs-mime-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	mime-types
PORTVERSION=	0.1.0.6
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic mime-type handling types and functions

LICENSE=	MIT

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
