# $FreeBSD: head/devel/hs-haskell-src/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	haskell-src
PORTVERSION=	1.0.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for manipulating Haskell source code

LICENSE=	BSD3CLAUSE

USE_HAPPY=	yes
USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
