# $FreeBSD: head/devel/hs-atomic-primops/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	atomic-primops
PORTVERSION=	0.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Safe approach to CAS and other atomic operations

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
