# New ports collection makefile for:	dlist
# Date created:				November 10, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: ports/devel/hs-dlist/Makefile,v 1.6 2010/05/12 16:33:42 pgj Exp $

PORTNAME=	dlist
PORTVERSION=	0.5
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A list-like type supporting O(1) append for Haskell

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
