# New ports collection makefile for:	dlist
# Date created:				November 10, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: head/devel/hs-dlist/Makefile 300896 2012-07-14 13:54:48Z beat $

PORTNAME=	dlist
PORTVERSION=	0.5
PORTREVISION=	6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A list-like type supporting O(1) append for Haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
