# $FreeBSD$

PORTNAME=	ekg
PORTVERSION=	0.3.1.3
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Remote monitoring of processes

LICENSE=	BSD

USE_CABAL=	aeson network snap-core snap-server text transformers \
		unordered-containers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
