# $FreeBSD$

PORTNAME=	random-shuffle
PORTVERSION=	0.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random shuffle implementation

LICENSE=	BSD

USE_CABAL=	MonadRandom random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
