# New ports collection makefile for: hs-QuickCheck
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-QuickCheck/Makefile,v 1.9 2011/05/26 00:50:54 ashish Exp $

PORTNAME=	QuickCheck
PORTVERSION=	2.4.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for random testing in haskell

LICENSE=	BSD

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
