# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-QuickCheck/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	QuickCheck
PORTVERSION=	2.8.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Automatic testing of Haskell programs

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions random tf-random>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
