# New ports collection makefile for: hs-QuickCheck
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-QuickCheck/Makefile,v 1.10 2012/02/13 04:13:20 pgj Exp $

PORTNAME=	QuickCheck
PORTVERSION=	2.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library for random testing in haskell

LICENSE=	BSD

USE_CABAL=	random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
