# $FreeBSD: head/security/hs-crypto-random/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-random
PORTVERSION=	0.0.9
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple cryptographic random related types

LICENSE=	BSD3CLAUSE

USE_CABAL=	securemem vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
