# New ports collection makefile for: hs-split
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-split/Makefile,v 1.5 2011/05/26 00:51:02 ashish Exp $
#

PORTNAME=	split
PORTVERSION=	0.1.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell combinator library for splitting lists

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
