# New ports collection makefile for: hs-split
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-split/Makefile 301897 2012-08-03 02:59:43Z pgj $
#

PORTNAME=	split
PORTVERSION=	0.1.4.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Combinator library for splitting lists

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
