# $FreeBSD$

PORTNAME=	cond
PORTVERSION=	0.4.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic conditional and boolean operators with monadic variants

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
