# New ports collection makefile for: hs-hxt-charproperties
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-hxt-charproperties/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	hxt-charproperties
PORTVERSION=	9.1.1
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
