# New ports collection makefile for: hs-hxt-charproperties
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-hxt-charproperties/Makefile,v 1.4 2012/06/03 20:52:24 pgj Exp $
#

PORTNAME=	hxt-charproperties
PORTVERSION=	9.1.1
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Character properties and classes for XML and Unicode

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
