# New ports collection makefile for: hs-transformers
# Date created:        December 20 2009
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-transformers-docs/Makefile,v 1.1 2011/05/08 19:25:15 ashish Exp $
#

PORTNAME=	transformers
PORTVERSION=	0.2.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for transformers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
