# New ports collection makefile for: hs-transformers
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-transformers/Makefile,v 1.4 2010/06/08 12:21:25 pgj Exp $
#

PORTNAME=	transformers
PORTVERSION=	0.2.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for transformers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
