# New ports collection makefile for: hs-transformers
# Date created:        December 20 2009
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-transformers-docs/Makefile,v 1.3 2012/02/13 03:49:26 pgj Exp $
#

PORTNAME=	transformers
PORTVERSION=	0.2.2.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for transformers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
