# New ports collection makefile for: hs-void
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	void
PORTVERSION=	0.5.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell 98 logically uninhabited data type

LICENSE=	BSD

USE_CABAL=	semigroups

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
