# New ports collection makefile for: hs-void
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-void/Makefile,v 1.2 2012/02/13 04:58:05 pgj Exp $
#

PORTNAME=	void
PORTVERSION=	0.5.5.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell 98 logically uninhabited data type

LICENSE=	BSD

USE_CABAL=	semigroups>=0.8.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
