# $FreeBSD: head/devel/hs-void/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	void
PORTVERSION=	0.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 logically uninhabited data type

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.1 semigroups>=0.8.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
