# New ports collection makefile for: hs-safe
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-safe/Makefile,v 1.3 2010/05/26 11:18:39 jacula Exp $
#

PORTNAME=	safe
PORTVERSION=	0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for safe (pattern match free) functions

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
