# New ports collection makefile for: hs-uuagc-cabal
# Date created:        August 12, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-uuagc-cabal/Makefile,v 1.1 2012/02/13 02:28:52 pgj Exp $
#

PORTNAME=	uuagc-cabal
PORTVERSION=	1.0.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cabal plugin for the Universiteit Utrecht Attribute Grammar System

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl>=2.0.1.0 uulib>=0.9.14

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
