# $FreeBSD: head/devel/hs-uuagc-cabal/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	uuagc-cabal
PORTVERSION=	1.0.6.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cabal plugin for the Universiteit Utrecht Attribute Grammar System

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0.1.0 uulib>=0.9.14

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
