# $FreeBSD: head/devel/hs-bifunctors/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bifunctors
PORTVERSION=	5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bifunctors

LICENSE=	BSD3CLAUSE

USE_CABAL=	semigroups>=0.8.3.1 tagged>=0.7.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
