# $FreeBSD: head/devel/hs-vector-binary-instances/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	vector-binary-instances
PORTVERSION=	0.2.1.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Instances of Data.Binary and Data.Serialize for vector

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal vector>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
