# $FreeBSD: head/devel/hs-byteable/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	byteable
PORTVERSION=	0.1.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type class for sequence of bytes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
