# New ports collection makefile for: hs-xml2html
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-xml2html/Makefile,v 1.1 2012/06/24 10:31:59 pgj Exp $
#

PORTNAME=	xml2html
PORTVERSION=	0.1.2.3
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	blaze-html instances for xml-conduit types

LICENSE=	BSD

USE_CABAL=	blaze-html>=0.5 blaze-markup>=0.5.1 text>=0.5 xml-conduit>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
