# New ports collection makefile for:	hs-zlib-conduit
# Date created:				December 30, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD: ports/archivers/hs-zlib-conduit/Makefile,v 1.1 2012/06/03 18:50:50 pgj Exp $

PORTNAME=	zlib-conduit
PORTVERSION=	0.4.0.1
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Streaming compression/decompression via conduits

LICENSE=	BSD

USE_CABAL=	conduit>=0.4 transformers>=0.2.2 zlib-bindings>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
