# New ports collection makefile for:	hs-utf8-string-ghc
# Date created:		2008-10-21
# Whom:			Ashish Shukla <wahjava@gmail.com>
#
# $FreeBSD: head/devel/hs-utf8-string/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	utf8-string
PORTVERSION=	0.3.7
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for reading/writing UTF-8 strings for Haskell programs

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
