# $FreeBSD$

PORTNAME=	monad-logger
PORTVERSION=	0.2.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A class of monads which can log messages

LICENSE=	MIT

CABAL_SETUP=	Setup.hs

USE_CABAL=	fast-logger>=0.2 resourcet>=0.3 text transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
