# $FreeBSD$

PORTNAME=	process-conduit
PORTVERSION=	1.0.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Conduits for processes

LICENSE=	BSD

USE_CABAL=	conduit control-monad-loop mtl>=2.0 shakespeare-text>=1.0 \
		text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
