# $FreeBSD$

PORTNAME=	process-conduit
PORTVERSION=	1.1.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Conduits for processes

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit>=1.1 control-monad-loop mtl>=2.0 resourcet>=1.1 \
		shakespeare text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
