# New ports collection makefile for:	hs-monadLib
# Date created:		2011-06-01
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	monadLib
PORTVERSION=	3.6.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A collection of monad transformers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
