# $FreeBSD$

PORTNAME=	uuid
PORTVERSION=	1.3.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Creating, comparing, parsing and printing Universally Unique Identifiers

LICENSE=	BSD3CLAUSE

USE_CABAL=	cryptohash>=0.7 network-info>=0.2 random>=1.0.1 uuid-types>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
