# $FreeBSD$

PORTNAME=	haskell-lexer
PORTVERSION=	1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fully-compliant Haskell 98 lexer

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
