# $FreeBSD$

PORTNAME=	dynamic-cabal
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Access the functions from the Cabal library without depending on it

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default ghc-paths haskell-generate haskell-src-exts \
		void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
