# $FreeBSD$

PORTNAME=	dynamic-cabal
PORTVERSION=	0.3.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Dynamically load the Cabal library

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default ghc-paths haskell-generate haskell-src-exts \
		void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
