# New ports collection makefile for: hs-blaze-html
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-blaze-html/Makefile,v 1.1 2011/08/13 19:41:48 pgj Exp $
#

PORTNAME=	blaze-html
PORTVERSION=	0.4.3.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A blazingly fast HTML combinator library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	blaze-builder>=0.2 text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
