# New ports collection makefile for: hs-blaze-html
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	blaze-html
PORTVERSION=	0.4.1.0
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A blazingly fast HTML combinator library

CABAL_SETUP=	Setup.hs

USE_HACKAGE=	blaze-builder text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
