# New ports collection makefile for: hs-mime
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/mail/hs-mime/Makefile 301901 2012-08-03 03:03:06Z pgj $
#

PORTNAME=	mime
PORTVERSION=	0.3.3.2
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Working with MIME types

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
