# New ports collection makefile for: hs-mime
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/mail/hs-mime/Makefile,v 1.3 2010/05/26 11:18:42 jacula Exp $
#

PORTNAME=	mime
PORTVERSION=	0.3.2
PORTREVISION=	1
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell library for working with MIME types

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
