# $FreeBSD$

PORTNAME=	gsasl
PORTVERSION=	0.3.5
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bindings for GNU libgsasl

LICENSE=	GPLv3
FILE_LICENSE=	license.txt

CABAL_SETUP=	Setup.hs

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
