# $FreeBSD$

PORTNAME=	either
PORTVERSION=	4.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Either monad transformer

LICENSE=	BSD3CLAUSE

USE_CABAL=	monad-control>=0.3.2 MonadRandom mtl>=2.0 semigroupoids>=4 \
		semigroups>=0.8.3.1 transformers>=0.2 transformers-base>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
