# $FreeBSD$

PORTNAME=	either
PORTVERSION=	3.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 either monad transformer

LICENSE=	BSD

USE_CABAL=	semigroupoids>=3.0 semigroups>=0.8.3.1 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
