# New ports collection makefile for: hs-semigroupoids
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-semigroupoids/Makefile 301903 2012-08-03 03:04:34Z pgj $
#

PORTNAME=	semigroupoids
PORTVERSION=	1.3.4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 semigroupoids: Category sans id

LICENSE=	BSD

USE_CABAL=	comonad>=1.1.1.5 contravariant>=0.2.0.1 semigroups>=0.8.3.1 \
		transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
