# $FreeBSD$

PORTNAME=	printxosd
PORTVERSION=	0.1
CATEGORIES=	x11 haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple tool to display some text on an on-screen display

LICENSE=	BSD3CLAUSE

USE_CABAL=	xosd
EXECUTABLE=	printxosd
STANDALONE=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
