# $FreeBSD: head/devel/hs-old-locale/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	old-locale
PORTVERSION=	1.0.0.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Locale library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
