# $FreeBSD$

PORTNAME=	unix-time
PORTVERSION=	0.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unix time parser/formatter and utilities

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
