# $FreeBSD: head/devel/hs-unix-time/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	unix-time
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unix time parser/formatter and utilities

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
