# $FreeBSD: head/devel/hs-data-default-instances-containers/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-default-instances-containers
PORTVERSION=	0.0.1
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Default instances for types in containers

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-default-class

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
