# $FreeBSD: head/www/hs-http-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	http-types
PORTVERSION=	0.8.6
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic HTTP types for Haskell (for both client and server code)

LICENSE=	BSD3CLAUSE

USE_CABAL=	blaze-builder>=0.2.1.4 case-insensitive>=0.2 text>=0.11.0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
