# $FreeBSD: head/security/hs-cipher-rc4/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cipher-rc4
PORTVERSION=	0.1.4
PORTREVISION=	2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast RC4 cipher implementation

LICENSE=	BSD3CLAUSE

USE_CABAL=	byteable crypto-cipher-types>=0.0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
