# $FreeBSD: head/devel/hs-timezone-series/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	timezone-series
PORTVERSION=	0.1.5.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enhanced timezone handling for Data.Time

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
