# $FreeBSD: head/devel/hs-Glob/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	Glob
PORTVERSION=	0.7.5
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Globbing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
