# $FreeBSD$

PORTNAME=	Glob
PORTVERSION=	0.7.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Globbing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist>=0.4 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
