# $FreeBSD: head/net-p2p/hs-torrent/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	torrent
PORTVERSION=	10000.0.0
CATEGORIES=	net-p2p haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	BitTorrent file parser and generater

LICENSE=	BSD3CLAUSE

USE_CABAL=	bencode>=0.2 syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
