# $FreeBSD: head/devel/hs-extensible-exceptions/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	extensible-exceptions
PORTVERSION=	0.1.1.4
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Extensible exceptions

LICENSE=	BSD3CLAUSE

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
