# $FreeBSD: head/devel/hs-reflection/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	reflection
PORTVERSION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reifies arbitrary terms into types that can be reflected back into terms

LICENSE=	BSD3CLAUSE

USE_CABAL=	tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
