# $FreeBSD$

PORTNAME=	transformers-compat
PORTVERSION=	0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lenses, Folds and Traversals

LICENSE=	BSD

USE_CABAL=	transformers>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
