# $FreeBSD: head/devel/hs-transformers-compat/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	transformers-compat
PORTVERSION=	0.4.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compatibility shim exposing the new types from transformers 0.3 and 0.4

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
