# $FreeBSD$

PORTNAME=	yi-rope
PORTVERSION=	0.7.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Rope data structure used by Yi

LICENSE=	GPLv2

USE_CABAL=	charsetdetect-ae>=1.0.1 data-default fingertree text \
		text-icu

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
