# $FreeBSD$

PORTNAME=	regex-tdfa-rc
PORTVERSION=	1.1.8.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl parsec regex-base>=0.93.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
