# $FreeBSD: head/devel/hs-map-syntax/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	map-syntax
PORTVERSION=	0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Syntax sugar for defining maps

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
