# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-ghc-paths/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ghc-paths
PORTVERSION=	0.1.0.9
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Knowledge of GHC's installation directories

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
