# New ports collection makefile for: hs-ghc-paths
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-ghc-paths/Makefile 300896 2012-07-14 13:54:48Z beat $

PORTNAME=	ghc-paths
PORTVERSION=	0.1.0.8
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utility looking for GHC installation directories

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
