# $FreeBSD$

PORTNAME=	snap-blaze
PORTVERSION=	0.2.1.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	blaze-html integration for Snap

LICENSE=	BSD

USE_CABAL=	blaze-html>=0.5 snap-core>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
