# New ports collection makefile for:	hs-ranges
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-ranges/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	ranges
PORTVERSION=	0.2.4
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Ranges and various functions on them

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
