# Created by:	martin@sugioarto.com
# $FreeBSD: head/devel/hs-BoundedChan/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	BoundedChan
PORTVERSION=	1.0.3.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Channels with bounded sizes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
