# New ports collection makefile for: hs-hslogger
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-hslogger/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	hslogger
PORTVERSION=	1.1.5
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Versatile logging framework for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
