# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-hslogger/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hslogger
PORTVERSION=	1.2.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Versatile logging framework

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl network old-locale

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
