# $FreeBSD: head/devel/hs-constraints/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	constraints
PORTVERSION=	0.4.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Constraint manipulation

LICENSE=	BSD3CLAUSE

USE_CABAL=	newtype>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
