# $FreeBSD$

PORTNAME=	fay-base
PORTVERSION=	0.18.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Base package for Fay

LICENSE=	BSD

USE_CABAL=	fay>=0.18

IGNORE_DYNAMIC=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
