# $FreeBSD$

PORTNAME=	fay-base
PORTVERSION=	0.20.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Base package for Fay

LICENSE=	BSD3CLAUSE

USE_CABAL=	fay>=0.21.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
