# New ports collection makefile for: hs-uvector
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-uvector/Makefile,v 1.4 2010/06/08 12:30:06 pgj Exp $
#

PORTNAME=	uvector
PORTVERSION=	0.1.1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast unboxed arrays with a flexible interface for Haskell

LICENSE=	BSD

BROKEN=		deprecated, use devel/hs-vector

PORTDATA=	*

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
