# $FreeBSD: head/devel/hs-time-compat/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	time-compat
PORTVERSION=	0.1.0.3
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compatibility with old-time for the time package

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-time

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
