# New ports collection makefile for:	hs-OpenGL-hp
# Date created:				April 23, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD$

MASTERDIR=	${.CURDIR}/../hs-OpenGL

MAINTAINER=	haskell@FreeBSD.org

PKGNAMESUFFIX=	-hp

WITH_PLATFORM=	yes

.include "${MASTERDIR}/Makefile"
