# $FreeBSD$

PORTNAME=	ltk
PORTVERSION=	0.12.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Leksah tool kit

LICENSE=	GPLv2

USE_CABAL=	glib>=0.10.0 gtk>=0.10.0 mtl>=1.1.0.2 parsec>=2.1.0.1 \
		transformers>=0.2.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
