# New ports collection makefile for: hs-ltk
# Date created:        May 11, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	ltk
PORTVERSION=	0.10.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Leksah tool kit

USE_CABAL=	glib>=0.10.0 gtk>=0.10.0 haddock mtl>=1.1.0.2 parsec>=2.1.0.1

#.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include "/usr/ports/lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
