# $FreeBSD$

PORTNAME=	ltk
PORTVERSION=	0.15.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Leksah tool kit

LICENSE=	GPLv2

USE_CABAL=	glib>=0.13.0.0 gtk3>=0.13.2 mtl>=1.1.0.2 parsec>=2.1.0.1 \
		text>=0.11.0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
