# $FreeBSD: head/devel/hs-data-default-class/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-default-class
PORTVERSION=	0.0.1
PORTREVISION=	7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Class for types with a default value

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
