# New ports collection makefile for: hs-TypeCompose
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-TypeCompose/Makefile,v 1.9 2012/06/03 20:52:10 pgj Exp $
#

PORTNAME=	TypeCompose
PORTVERSION=	0.9.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type composition classes and instances

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
