# $FreeBSD$

PORTNAME=	xosd
PORTVERSION=	0.2.1
CATEGORIES=	x11 haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A binding to the X on-screen display

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libxosd.so:${PORTSDIR}/misc/xosd

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
