# New ports collection makefile for:	hs-xosd
# Date created:				November 19, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	xosd
PORTVERSION=	0.2
CATEGORIES=	x11 haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A binding to the X on-screen display

LICENSE=	BSD

LIB_DEPENDS=	xosd:${PORTSDIR}/misc/xosd

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
