# $FreeBSD: head/devel/hs-chunked-data/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	chunked-data
PORTVERSION=	0.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclasses for dealing with various chunked data representations

LICENSE=	MIT

USE_CABAL=	blaze-builder mono-traversable>=0.2 semigroups text>=0.11 \
		vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
