# $FreeBSD$

PORTNAME=	wl-pprint-text
PORTVERSION=	1.1.0.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Wadler/Leijen Pretty Printer for Text values

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=0.11.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
