# New ports collection makefile for: hs-wl-pprint-text
# Date created:        June 5, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	wl-pprint-text
PORTVERSION=	1.1.0.0
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Wadler/Leijen Pretty Printer for Text values

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	text>=0.11.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
