# New ports collection makefile for: hs-ObjectName
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-ObjectName/Makefile,v 1.6 2012/02/13 03:49:20 pgj Exp $
#

PORTNAME=	ObjectName
PORTVERSION=	1.0.0.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Explicitly handled object names for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
