# New ports collection makefile for: hs-email-validate
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/mail/hs-email-validate/Makefile,v 1.2 2012/06/03 22:08:56 pgj Exp $
#

PORTNAME=	email-validate
PORTVERSION=	0.2.8
PORTREVISION=	1
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Validating an email address string against RFC 5322

LICENSE=	BSD

USE_CABAL=	parsec ranges>=0.2.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
