# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-datetime/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	datetime
PORTVERSION=	0.3.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities to make Data.Time.* easier to use

LICENSE=	GPLv3

USE_CABAL=	old-locale>=1.0.0.1 old-time>=1.0.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
