# New ports collection makefile for: hs-datetime
# Date created:        December 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-datetime/Makefile,v 1.9 2012/06/03 20:52:11 pgj Exp $
#

PORTNAME=	datetime
PORTVERSION=	0.2.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities to make Data.Time.* easier to use in Haskell

LICENSE=	GPLv3
FILE_LICENSE=	COPYING

USE_CABAL=	QuickCheck>=2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
