# $FreeBSD$

PORTNAME=	filesystem-trees
PORTVERSION=	0.1.0.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Recursively manipulate and traverse filesystems as lazy rose trees

LICENSE=	BSD3CLAUSE

USE_CABAL=	cond>=0.3 data-lens>=2.0.1 dlist>=0.2 mtl>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
