# New ports collection makefile for: hs-unamb
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-unamb/Makefile,v 1.7 2012/06/03 22:01:00 pgj Exp $
#

PORTNAME=	unamb
PORTVERSION=	0.2.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unambiguous choice

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
