# New ports collection makefile for: hs-unamb
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-unamb/Makefile,v 1.3 2010/05/26 11:18:40 jacula Exp $
#

PORTNAME=	unamb
PORTVERSION=	0.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Unambiguous choice library for Haskell

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
