# New ports collection makefile for: hs-xhtml
# Date created:        September 15, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-xhtml/Makefile,v 1.2 2011/05/25 18:57:25 ashish Exp $
#

PORTNAME=	xhtml
PORTVERSION=	3000.2.0.1
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An XHTML combinator library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
