# New ports collection makefile for: hs-xhtml
# Date created:        September 15, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-xhtml/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	xhtml
PORTVERSION=	3000.2.1
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An XHTML combinator library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
