# New ports collection makefile for: hs-xhtml
# Date created:        September 15, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-xhtml/Makefile,v 1.4 2012/06/03 22:34:58 pgj Exp $
#

PORTNAME=	xhtml
PORTVERSION=	3000.2.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An XHTML combinator library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
