# New ports collection makefile for: hs-PSQueue
# Date created:        September 20, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-PSQueue/Makefile,v 1.2 2012/02/13 04:12:18 pgj Exp $
#

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
