# New ports collection makefile for: hs-PSQueue
# Date created:        September 20, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-PSQueue/Makefile,v 1.3 2012/06/03 20:52:09 pgj Exp $
#

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
