# New ports collection makefile for: hs-PSQueue
# Date created:        September 20, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-PSQueue/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	PSQueue
PORTVERSION=	1.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Priority Search Queue

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
