# New ports collection makefile for: hs-xml
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/textproc/hs-xml/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	xml
PORTVERSION=	1.3.12
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A simple XML library for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
