# New ports collection makefile for: hs-MemoTrie
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-MemoTrie/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	MemoTrie
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Trie-based memo functions

LICENSE=	BSD
FILE_LICENSE=	COPYING

USE_CABAL=	void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
