# New ports collection makefile for: hs-MemoTrie
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-MemoTrie/Makefile,v 1.4 2011/05/09 05:28:31 ashish Exp $
#

PORTNAME=	MemoTrie
PORTVERSION=	0.4.9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Trie-based memo functions for Haskell

LICENSE=	BSD
FILE_LICENSE=	COPYING

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
