# New ports collection makefile for: hs-MemoTrie
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-MemoTrie/Makefile,v 1.7 2012/02/13 03:49:20 pgj Exp $
#

PORTNAME=	MemoTrie
PORTVERSION=	0.4.12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Trie-based memo functions

LICENSE=	BSD
FILE_LICENSE=	COPYING

USE_CABAL=	void

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
