# $FreeBSD$

PORTNAME=	language-java
PORTVERSION=	0.2.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Manipulating Java source: abstract syntax, lexer, parser, and pretty-printer

LICENSE=	BSD

USE_CABAL=	cpphs>=1.3 parsec>=3.0 syb
USE_ALEX=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
