# $FreeBSD$

PORTNAME=	hasktags
PORTVERSION=	0.68.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Produces ctags "tags" and etags "TAGS" files for Haskell programs

LICENSE=	BSD

USE_CABAL=	json>=0.5

EXECUTABLE=	hasktags

STANDALONE=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
