# $FreeBSD: head/security/hs-crypto-random-api/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-random-api
PORTVERSION=	0.2.0
PORTREVISION=	8
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple random generators API for cryptography related code

LICENSE=	BSD3CLAUSE

USE_CABAL=	entropy

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
