# $FreeBSD: head/devel/hs-hslua/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hslua
PORTVERSION=	0.4.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lua language interpreter embedding in Haskell

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
