# New ports collection makefile for: hs-HTTP
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/www/hs-HTTP/Makefile,v 1.7 2012/06/03 22:36:47 pgj Exp $
#

PORTNAME=	HTTP
PORTVERSION=	4000.2.3
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A Haskell library for client-side HTTP

LICENSE=	BSD

USE_CABAL=	mtl network parsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
