# $FreeBSD: head/devel/hs-threads/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	threads
PORTVERSION=	0.5.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fork threads and wait for their result

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm>=2.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
