# New ports collection makefile for: hs-readline
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-readline/Makefile,v 1.6 2011/05/26 00:51:01 ashish Exp $

PORTNAME=	readline
PORTVERSION=	1.0.1.0
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell interface to the GNU readline library

LICENSE=	GPLv2

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
