# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-readline/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	readline
PORTVERSION=	1.0.3.0
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface to the GNU readline library

LICENSE=	GPLv2

USES=		readline

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
