# $FreeBSD$

PORTNAME=	yesod-platform
PORTVERSION=	1.1.4.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Meta package for Yesod

LICENSE=	MIT

USE_CABAL=	aeson==0.6.0.2_1 ansi-terminal==0.5.5_4 asn1-data==0.7.1 \
		attoparsec==0.10.2.0_1 attoparsec-conduit==0.5.0.2 \
		authenticate==1.3.1.1 base-unicode-symbols==0.2.2.4 \
		base64-bytestring==1.0.0.0 blaze-builder==0.3.1.0_2 \
		blaze-builder-conduit==0.5.0.1 blaze-html==0.5.1.0 \
		blaze-markup==0.5.1.1 byteorder==1.0.3_2 \
		case-insensitive==0.4.0.3 cereal==0.3.5.2 certificate==1.2.8 \
		clientsession==0.8.0.1 conduit==0.5.2.7 cookie==0.4.0.1 \
		cprng-aes==0.2.4 cpu==0.1.1 crypto-api==0.10.2_1 \
		crypto-conduit==0.4.0.1 crypto-pubkey-types==0.1.1_1 \
		cryptocipher==0.3.5 cryptohash==0.7.5_1 css-text==0.1.1_2 \
		data-default==0.5.0 date-cache==0.3.0 dlist==0.5_6 \
		email-validate==0.2.8_1 entropy==0.2.1_2 failure==0.2.0.1_1 \
		fast-logger==0.3.1 file-embed==0.0.4.6 filesystem-conduit==0.5.0.1 \
		hamlet==1.1.1 hashable==1.1.2.5 hjsmin==0.1.3 hspec==1.3.0.1 \
		hspec-expectations==0.3.0.2 html-conduit==0.1.0.2 \
		http-conduit==1.6.1.2 http-date==0.0.2_1 http-types==0.7.3.0.1 \
		language-javascript==0.5.6 largeword==1.0.3 lifted-base==0.2 \
		mime-mail==0.4.1.2 mime-types==0.1.0.0 monad-control==0.3.1.4 \
		monad-logger==0.2.1 network-conduit==0.6.1.1 \
		path-pieces==0.1.2 pem==0.1.1_1 persistent==1.0.1.3 \
		persistent-template==1.0.0.2 pool-conduit==0.1.0.3 \
		primitive==0.5.0.1 pureMD5==2.1.2.1 pwstore-fast==2.3 \
		ranges==0.2.4_2 resource-pool==0.2.1.1 resourcet==0.4.0.2 \
		safe==0.3.3_2 semigroups==0.8.4.1 SHA==1.5.1 shakespeare==1.0.1.4 \
		shakespeare-css==1.0.1.5 shakespeare-i18n==1.0.0.2_1 \
		shakespeare-js==1.0.0.6 shakespeare-text==1.0.0.5 \
		silently==1.2.0.2 simple-sendfile==0.2.8 skein==0.1.0.9 \
		socks==0.4.2 stringsearch==0.3.6.4 system-fileio==0.3.10 \
		system-filepath==0.4.7 tagged==0.4.4 tagsoup==0.12.8 \
		tagstream-conduit==0.5.3 tar==0.4.0.1 tls==0.9.11 \
		tls-extra==0.4.7 transformers-base==0.4.1_2 unix-compat==0.4.0.0 \
		unordered-containers==0.2.2.1 utf8-light==0.4.0.1_1 \
		utf8-string==0.3.7_2 vault==0.2.0.1 vector==0.10.0.1 void==0.5.8 \
		wai==1.3.0.1 wai-app-static==1.3.0.2 wai-extra==1.3.0.3 \
		wai-logger==0.3.0 wai-test==1.3.0 warp==1.3.4.1 \
		xml-conduit==1.0.3.1 xml-types==0.3.3 xss-sanitize==0.3.2_1 \
		yaml==0.8.1 yesod==1.1.2 yesod-auth==1.1.1.2 \
		yesod-core==1.1.3.1 yesod-default==1.1.0.2 yesod-form==1.1.3 \
		yesod-json==1.1.0 yesod-persistent==1.1.0 yesod-routes==1.1.0.2 \
		yesod-static==1.1.0.1 yesod-test==0.3.0.1 zlib-bindings==0.1.1.1 \
		zlib-conduit==0.5.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
