# New ports collection makefile for: hs-case-insensitive
# Date created:        May 24, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-case-insensitive/Makefile,v 1.1 2011/07/10 21:26:42 ashish Exp $
#

PORTNAME=	case-insensitive
PORTVERSION=	0.2.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Case insensitive string comparison

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	text>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
