# $FreeBSD$

PORTNAME=	fay-jquery
PORTVERSION=	0.6.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	jQuery bindings for Fay

LICENSE=	BSD3CLAUSE

USE_CABAL=	fay-base>=0.18 fay-text>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
