# $FreeBSD$

PORTNAME=	fay-jquery
PORTVERSION=	0.4.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	jQuery bindings for Fay

LICENSE=	BSD

USE_CABAL=	fay-base>=0.17 fay-text>=0.1

IGNORE_DYNAMIC=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
