# $FreeBSD$

PORTNAME=	fay-jquery
PORTVERSION=	0.3.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	jQuery binding

LICENSE=	BSD

USE_CABAL=	fay-base>=0.14.1.0

IGNORE_DYNAMIC=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
