# $FreeBSD$

PORTNAME=	attoparsec-iteratee
PORTVERSION=	0.4.0
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An adapter to convert attoparsec Parsers into blazing-fast Iteratees

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec>=0.8 iteratee>=0.7 transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
