# $FreeBSD: head/devel/hs-base-orphans/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	base-orphans
PORTVERSION=	0.4.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Backwards-compatible orphan instances for base

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
