# $FreeBSD: head/devel/hs-uuid-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	uuid-types
PORTVERSION=	1.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type definitions for Universally Unique Identifiers

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable>=1.1.1.0 random>=1.0.1 text>=1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
