# $FreeBSD$

PORTNAME=	uuid-types
PORTVERSION=	1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type definitions for Universally Unique Identifiers

LICENSE=	BSD3CLAUSE

USE_CABAL=	hashable random>=1.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
