# New ports collection makefile for: hs-colour
# Date created:        June 5, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	colour
PORTVERSION=	2.3.3
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A model for human colour/color perception

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
