# $FreeBSD: head/textproc/hs-xml-hamlet/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	xml-hamlet
PORTVERSION=	0.4.0.11
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Hamlet-style quasiquoter for XML content

LICENSE=	BSD3CLAUSE

USE_CABAL=	parsec>=2.0 shakespeare>=1.0 text>=0.10 xml-conduit>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
