# $FreeBSD$

PORTNAME=	cipher-aes
PORTVERSION=	0.1.2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast AES cipher implementation with advanced mode of operations

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_GCC=	4.6+

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
