# New ports collection makefile for: hs-ghc-events
# Date created:        December 6, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-ghc-events/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	ghc-events
PORTVERSION=	0.4.0.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library and tool for parsing .eventlog files from GHC

LICENSE=	BSD

USE_CABAL=	mtl>=1.1

EXECUTABLE=	ghc-events

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
