# $FreeBSD: head/devel/hs-ghc-events/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ghc-events
PORTVERSION=	0.4.4.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library and tool for parsing .eventlog files from GHC

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.2.1

EXECUTABLE=	ghc-events

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
