# New ports collection makefile for:	binary
# Date created:				December 15, 2008
# Whom:					Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-binary/Makefile,v 1.11 2010/05/24 21:52:30 pgj Exp $
#

PORTNAME=	binary
PORTVERSION=	0.5.0.2
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient binary serialisation for Haskell

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
