# New ports collection makefile for:	binary
# Date created:				December 15, 2008
# Whom:					Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-binary/Makefile,v 1.14 2012/02/13 03:49:21 pgj Exp $
#

PORTNAME=	binary
PORTVERSION=	0.5.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Binary serialisation for Haskell values using lazy ByteStrings

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
