# $FreeBSD$

PORTNAME=	haskell-packages
PORTVERSION=	0.2.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell suite library for package management and integration with Cabal

LICENSE=	MIT

USE_CABAL=	aeson>=0.6 either haskell-src-exts>=1.14 hse-cpp mtl>=2.1 \
		optparse-applicative>=0.6 tagged

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
