# New ports collection makefile for: hs-Diff
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/textproc/hs-Diff/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	Diff
PORTVERSION=	0.1.3
PORTREVISION=	2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	O(ND) diff algorithm in haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
