# New ports collection makefile for: hs-Diff
# Date created:        January 10 2010
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/textproc/hs-Diff/Makefile,v 1.6 2012/02/13 05:23:27 pgj Exp $
#

PORTNAME=	Diff
PORTVERSION=	0.1.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	O(ND) diff algorithm in haskell

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
