# New ports collection makefile for: hs-xml-types
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-xml-types/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	xml-types
PORTVERSION=	0.3.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic types for representing XML

LICENSE=	MIT
FILE_LICENSE=	license.txt

CABAL_SETUP=	Setup.hs

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
