# New ports collection makefile for: hs-xml-types
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-xml-types/Makefile,v 1.1 2012/02/18 16:30:09 pgj Exp $
#

PORTNAME=	xml-types
PORTVERSION=	0.3.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Basic types for representing XML

LICENSE=	MIT
FILE_LICENSE=	license.txt

CABAL_SETUP=	Setup.hs

USE_CABAL=	text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
