# New ports collection makefile for: hs-silently
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-silently/Makefile,v 1.1 2012/06/24 10:12:27 pgj Exp $
#

PORTNAME=	silently
PORTVERSION=	1.2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
