# New ports collection makefile for: hs-silently
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-silently/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	silently
PORTVERSION=	1.2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
