# $FreeBSD: head/devel/hs-silently/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	silently
PORTVERSION=	1.2.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prevent or capture writing to stdout and other handles

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
