# $FreeBSD: head/devel/hs-simple-reflect/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	simple-reflect
PORTVERSION=	0.3.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple reflection of expressions containing variables

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
