# $FreeBSD$

PORTNAME=	snaplet-fay
PORTVERSION=	0.3.3.12
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fay integration for Snap with request- and pre-compilation

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson>=0.6 configurator>=0.2 fay>=0.20 mtl>=2.1 snap>=0.11.1 \
		snap-core>=0.9.3.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
