# $FreeBSD: head/devel/hs-random/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	random
PORTVERSION=	1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random number library

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
