# $FreeBSD$

PORTNAME=	fay-text
PORTVERSION=	0.3.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fay Text type represented as JavaScript strings

LICENSE=	MIT

USE_CABAL=	fay>=0.21.2 fay-base>=0.19.4 text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
