# $FreeBSD$

PORTNAME=	fay-text
PORTVERSION=	0.1.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fay Text type represented as JavaScript strings

LICENSE=	MIT

USE_CABAL=	fay>=0.17 fay-base>=0.17 text

IGNORE_DYNAMIC=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
