# New ports collection makefile for: hs-MonadCatchIO-transformers
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-MonadCatchIO-transformers/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	MonadCatchIO-transformers
PORTVERSION=	0.3.0.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer-compatible version of Control.Exception

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
