# $FreeBSD: head/devel/hs-MonadCatchIO-transformers/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	MonadCatchIO-transformers
PORTVERSION=	0.3.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer-compatible version of Control.Exception

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions monads-tf

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
