# New ports collection makefile for: hs-MonadCatchIO-transformers
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-MonadCatchIO-transformers/Makefile,v 1.2 2012/02/13 04:11:12 pgj Exp $
#

PORTNAME=	MonadCatchIO-transformers
PORTVERSION=	0.3.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad-transformer-compatible version of Control.Exception

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
