# $FreeBSD$

PORTNAME=	data-binary-ieee754
PORTVERSION=	0.4.4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parser/Serialiser for IEEE-754 floating-point values

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
