# New ports collection makefile for: hs-shakespeare-css
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-shakespeare-css/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	shakespeare-css
PORTVERSION=	1.0.1.2
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Stick your Haskell variables into CSS at compile time

LICENSE=	MIT

USE_CABAL=	parsec>=2 shakespeare>=1.0 text>=0.11.1.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
