# New ports collection makefile for: hs-shakespeare-css
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare-css/Makefile,v 1.1 2012/02/18 17:28:38 pgj Exp $
#

PORTNAME=	shakespeare-css
PORTVERSION=	0.10.6
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Stick your Haskell variables into CSS at compile time

LICENSE=	BSD

USE_CABAL=	parsec>=2 shakespeare>=0.10 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
