# $FreeBSD: head/devel/hs-haddock-library/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	haddock-library
PORTVERSION=	1.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Library exposing some functionality of Haddock

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
