# New ports collection makefile for:	hs-GLUT-hp
# Date created:				April 23, 2011
# Whom:					haskell@FreeBSD.org
#
# $FreeBSD$

MASTERDIR=	${.CURDIR}/../hs-GLUT

MAINTAINER=	haskell@FreeBSD.org

PKGNAMESUFFIX=	-hp

WITH_PLATFORM=	yes

.include "${MASTERDIR}/Makefile"
