# $FreeBSD$

PORTNAME=	mime-string
PORTVERSION=	0.4
CATEGORIES=	mail haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	MIME implementation for String's

USE_CABAL=	base64-string iconv mtl network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
