# $FreeBSD: head/devel/hs-timezone-olson/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	timezone-olson
PORTVERSION=	0.1.7
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Pure Haskell parser and renderer for binary Olson timezone files

LICENSE=	BSD3CLAUSE

USE_CABAL=	extensible-exceptions>=0.1.0 timezone-series>=0.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
