# $FreeBSD$

PORTNAME=	mono-traversable
PORTVERSION=	0.2.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes for mapping, folding, and traversing monomorphic containers

LICENSE=	MIT

USE_CABAL=	comonad>=3.0.3 hashable semigroupoids>=3.0 semigroups>=0.9 \
		text>=0.11 transformers>=0.3 unordered-containers>=0.2 \
		vector>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
