# $FreeBSD: head/devel/hs-vector-th-unbox/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	vector-th-unbox
PORTVERSION=	0.2.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Deriver for Data.Vector.Unboxed using Template Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
