# $FreeBSD: head/devel/hs-optparse-applicative/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	optparse-applicative
PORTVERSION=	0.11.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities and combinators for parsing command line options

LICENSE=	BSD3CLAUSE

USE_CABAL=	ansi-wl-pprint>=0.6 transformers-compat>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
