# $FreeBSD: head/textproc/hs-rfc5051/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	rfc5051
PORTVERSION=	0.1.0.3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple unicode collation as per RFC5051

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
