# $FreeBSD$

PORTNAME=	tasty-hunit
PORTVERSION=	0.8.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HUnit support for the Tasty test framework

LICENSE=	MIT

USE_CABAL=	HUnit mtl tasty>=0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
