# New ports collection makefile for: hs-Tensor
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-Tensor/Makefile,v 1.6 2012/02/13 03:49:21 pgj Exp $
#

PORTNAME=	Tensor
PORTVERSION=	1.0.0.1
PORTREVISION=	3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Tensor data types for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
