# $FreeBSD$

PORTNAME=	language-ecmascript
PORTVERSION=	0.15.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	JavaScript parser and pretty-printer library

LICENSE=	BSD

USE_CABAL=	data-default-class>=0.0.1 Diff mtl>=1 parsec>3 \
		QuickCheck>=2.5 uniplate>=1.6 wl-pprint

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
