# $FreeBSD$

PORTNAME=	language-ecmascript
PORTVERSION=	0.14
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	JavaScript analysis tools

LICENSE=	BSD

USE_CABAL=	charset>=0.3.2.1 data-default>=0.4 mtl>=1.1.0.1 parsec \
		QuickCheck>=2.5 syb>=0.1 uniplate>=1.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
