# $FreeBSD$

PORTNAME=	language-ecmascript
PORTVERSION=	0.15.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	JavaScript parser and pretty-printer library

LICENSE=	BSD

USE_CABAL=	data-default-class>=0.0.1 Diff mtl>=1.1.0.1 parsec \
		QuickCheck>=2.5 uniplate>=1.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
