# $FreeBSD$

PORTNAME=	lens
PORTVERSION=	3.7.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lenses, Folds and Traversals

LICENSE=	BSD

USE_CABAL=	comonad>=3 comonad-transformers>=3 comonads-fd>=3 \
		hashable>=1.1.2.3 mtl>=2.0.1 nats>=0.1 parallel>=3.1.0.1 \
		semigroups>=0.8.4 split text>=0.11 transformers>=0.2 \
		transformers-compat>=0.1 unordered-containers>=0.2 \
		vector>=0.9

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
