# $FreeBSD$

PORTNAME=	lens
PORTVERSION=	3.10.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lenses, Folds and Traversals

LICENSE=	BSD

USE_CABAL=	bifunctors>=4 comonad>=4 contravariant>=0.3 distributive>=0.3 \
		generic-deriving>=1.4 hashable>=1.1.2.3 \
		MonadCatchIO-transformers>=0.3 mtl>=2.0.1 parallel>=3.1.0.1 \
		profunctors>=4 reflection>=1.1.6 semigroupoids>=4 \
		semigroups>=0.8.4 split>=0.2 tagged>=0.4.4 text>=0.11 \
		transformers>=0.3 unordered-containers>=0.2 vector>=0.9 \
		void>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
