# $FreeBSD: head/math/hs-categories/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	categories
PORTVERSION=	1.0.7
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Categories

LICENSE=	BSD3CLAUSE

USE_CABAL=	void>=0.5.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
