# New ports collection makefile for: hs-categories
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-categories/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	categories
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Categories from category-extras

LICENSE=	BSD

USE_CABAL=	void>=0.5.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
