# New ports collection makefile for: hs-comonad
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-comonad/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	comonad
PORTVERSION=	1.1.1.6
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 comonads

LICENSE=	BSD

USE_CABAL=	semigroups>=0.8.3.1 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
