# $FreeBSD$

PORTNAME=	comonad
PORTVERSION=	4.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Comonads

LICENSE=	BSD

USE_CABAL=	contravariant>=0.2.0.1 distributive>=0.2.2 mtl>=2.0 \
		semigroups>=0.8.3.1 tagged>=0.1 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
