# $FreeBSD: head/math/hs-comonad/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	comonad
PORTVERSION=	4.2.7.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Comonads

LICENSE=	BSD3CLAUSE

USE_CABAL=	contravariant>=0.2.0.1 distributive>=0.2.2 semigroups>=0.8.3.1 \
		tagged>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
