# New ports collection makefile for: hs-hscolour-docs
# Date created:        February 22 2008
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/print/hs-hscolour-docs/Makefile,v 1.12 2010/05/26 11:18:44 jacula Exp $
#

PORTNAME=	hscolour
PORTVERSION=	1.17
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for HsColour

CABAL_SETUP=	Setup.hs

LICENSE=	GPLv2
LICENSE_FILE=	${WKRSRC}/LICENCE-GPL

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
