# $FreeBSD$

PORTNAME=	data-lens
PORTVERSION=	2.10.4
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 lenses

LICENSE=	BSD

USE_CABAL=	comonad>=4.0 semigroupoids>=4.0 transformers>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
