# New ports collection makefile for: hs-data-lens
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-data-lens/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	data-lens
PORTVERSION=	2.10.0
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 lenses

LICENSE=	BSD

USE_CABAL=	comonad>=1.1.1.3 comonad-transformers>=2.0 \
		semigroupoids>=1.2.4 transformers>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
