# New ports collection makefile for: hs-data-lens
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-data-lens/Makefile,v 1.1 2012/02/13 02:33:04 pgj Exp $
#

PORTNAME=	data-lens
PORTVERSION=	2.10.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell 98 lenses

LICENSE=	BSD

USE_CABAL=	comonad>=1.1.1.3 comonad-transformers>=2.0 \
		semigroupoids>=1.2.4 transformers>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
