# $FreeBSD$

PORTNAME=	gnuidn
PORTVERSION=	0.2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bindings for GNU IDN

LICENSE=	GPLv3
FILE_LICENSE=	license.txt

CABAL_SETUP=	Setup.hs

USE_CABAL=	text
USE_C2HS=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
