# $FreeBSD: head/devel/hs-asn1-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	asn1-types
PORTVERSION=	0.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	ASN.1 types

LICENSE=	BSD3CLAUSE

USE_CABAL=	hourglass

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
