# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD: head/math/hs-math-functions/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	math-functions
PORTVERSION=	0.1.5.2
PORTREVISION=	2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Special functions and Chebyshev polynomials

LICENSE=	BSD3CLAUSE

USE_CABAL=	erf>=2 vector>=0.7 vector-th-unbox

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
