# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD$

PORTNAME=	math-functions
PORTVERSION=	0.1.4.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Special functions and Chebyshev polynomials

LICENSE=	BSD3CLAUSE

USE_CABAL=	erf>=2 vector>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
