# $FreeBSD: head/devel/hs-bytestring-nums/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bytestring-nums
PORTVERSION=	0.3.6
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse numeric literals from ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
