# New ports collection makefile for: hs-bytestring-nums
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-bytestring-nums/Makefile,v 1.1 2011/08/13 20:33:23 pgj Exp $
#

PORTNAME=	bytestring-nums
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse numeric literals from ByteStrings

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

EXECUTABLE=	spoj-eugene

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
