# New ports collection makefile for: hs-primitive
# Date created:        June 5, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-primitive/Makefile,v 1.3 2011/05/26 00:51:01 ashish Exp $
#

PORTNAME=	primitive
PORTVERSION=	0.4.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Wrappers for primitive operations

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
