# $FreeBSD: head/devel/hs-primitive/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	primitive
PORTVERSION=	0.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Primitive memory-related operations

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
