# $FreeBSD: head/net/hs-network-multicast/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	network-multicast
PORTVERSION=	0.1.0
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple multicast library

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
