# $FreeBSD: head/devel/hs-lifted-base/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	lifted-base
PORTVERSION=	0.2.3.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lifted IO operations from the base library

LICENSE=	BSD3CLAUSE

USE_CABAL=	monad-control>=0.3 transformers-base>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
