# $FreeBSD: head/devel/hs-data-ordlist/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-ordlist
PORTVERSION=	0.4.7.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Set and bag operations on ordered lists

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
