# New ports collection makefile for:	hs-fclabels
# Date created:		December 8, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	fclabels
PORTVERSION=	1.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	First-class accessor labels

LICENSE=	BSD

USE_CABAL=	mtl>=1.0 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
