# $FreeBSD$

PORTNAME=	fclabels
PORTVERSION=	2.0.2.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	First-class accessor labels implemented as lenses

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
