# $FreeBSD$

PORTNAME=	fclabels
PORTVERSION=	1.1.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	First-class accessor labels

LICENSE=	BSD

USE_CABAL=	mtl>=1.0 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
