# $FreeBSD$

PORTNAME=	tasty-th
PORTVERSION=	0.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Automagically generate the HUnit- and Quickcheck code using Template Haskell

LICENSE=	BSD3CLAUSE

USE_CABAL=	language-haskell-extract>=0.2 tasty

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
