# New ports collection makefile for: hs-vector
# Date created:        June 5, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-vector/Makefile,v 1.4 2011/05/26 00:51:05 ashish Exp $
#

PORTNAME=	vector
PORTVERSION=	0.7.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient Arrays

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	primitive>=0.3.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
