# $FreeBSD: head/devel/hs-vector/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	vector
PORTVERSION=	0.10.12.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient Arrays

LICENSE=	BSD3CLAUSE

USE_CABAL=	primitive>=0.5.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
