# New ports collection makefile for: hs-vector-algorithms
# Date created:        June 5, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-vector-algorithms/Makefile,v 1.2 2011/05/09 05:28:45 ashish Exp $
#

PORTNAME=	vector-algorithms
PORTVERSION=	0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient algorithms for vector arrays

LICENSE=	BSD

USE_CABAL=	primitive>=0.3 vector>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
