# New ports collection makefile for: hs-test-framework-hunit
# Date created:        May 21, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: head/devel/hs-test-framework-hunit/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	test-framework-hunit
PORTVERSION=	0.2.7
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HUnit support for the test-framework package

LICENSE=	BSD

USE_CABAL=	HUnit>=1.2 test-framework>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
