# New ports collection makefile for: hs-test-framework-hunit
# Date created:        May 21, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-test-framework-hunit/Makefile,v 1.3 2011/05/26 00:51:03 ashish Exp $
#

PORTNAME=	test-framework-hunit
PORTVERSION=	0.2.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HUnit support for the test-framework package

LICENSE=	BSD

USE_CABAL=	HUnit>=1.2 test-framework>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
