# $FreeBSD$

PORTNAME=	esqueleto
PORTVERSION=	2.2.10
CATEGORIES=	databases haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type-safe EDSL for SQL queries on persistent backends

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit>=1.1 monad-logger persistent>=2.1.1.7 resourcet>=1.1 \
		tagged>=0.2 text>=0.11 unordered-containers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
