# New ports collection makefile for: hs-blaze-textual-native
# Date created:        November 24, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	blaze-textual-native
PORTVERSION=	0.2.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast rendering of common data types

LICENSE=	BSD

USE_CABAL=	blaze-builder>=0.2.1.4 text>=0.11.0.2 vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
