# $FreeBSD: head/devel/hs-blaze-builder/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	blaze-builder
PORTVERSION=	0.4.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient buffered output

LICENSE=	BSD3CLAUSE

USE_CABAL=	text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
