# New ports collection makefile for: hs-blaze-builder
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-blaze-builder/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	blaze-builder
PORTVERSION=	0.3.1.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient buffered output

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
