# New ports collection makefile for: hs-blaze-builder
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-blaze-builder/Makefile,v 1.3 2011/07/10 16:30:17 ashish Exp $
#

PORTNAME=	blaze-builder
PORTVERSION=	0.3.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient buffered output

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	text>=0.10

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
