# $FreeBSD$

PORTNAME=	base64-string
PORTVERSION=	0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Base64 implementation for String's

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
