# $FreeBSD: head/devel/hs-DrIFT/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	DrIFT
PORTVERSION=	2.4.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Program to derive type class instances

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-time random

EXECUTABLE=	DrIFT drift-ghc

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
