# $FreeBSD$

PORTNAME=	fingertree
PORTVERSION=	0.0.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic finger-tree structure, with example instances

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
