# New ports collection makefile for:	hs-data-object-yaml
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	data-object-yaml
PORTVERSION=	0.3.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Serialize data to and from Yaml files

LICENSE=	BSD

USE_CABAL=	conduit convertible-text>=0.3.0 data-object>=0.3.0 \
		failure>=0.1.0 text>=0.7 transformers>=0.2 yaml>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
