# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-ghc-mtl/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ghc-mtl
PORTVERSION=	1.2.1.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Mtl-compatible version of the Ghc-Api monads and monad-transformers

LICENSE=	BSD3CLAUSE

USE_CABAL=	exceptions>=0.6 extensible-exceptions mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
