# $FreeBSD$

PORTNAME=	vcswrapper
PORTVERSION=	0.1.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Wrapper for source code management systems

LICENSE=	GPLv2

USE_CABAL=	hxt>=9.1.2 mtl>=2.0.1.0 parsec>=3.1.1 split>=0.2.2 \
		text>=0.11.1.5

EXECUTABLE=	vcswrapper

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
