# $FreeBSD$

PORTNAME=	regex-tdfa-text
PORTVERSION=	1.0.0.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Text interface for regex-tdfa

LICENSE=	BSD3CLAUSE

USE_CABAL=	regex-base regex-tdfa>=1.1.1 text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
