# New ports collection makefile for: hs-stm
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-stm/Makefile,v 1.1 2011/05/08 19:21:29 ashish Exp $
#

PORTNAME=	stm
PORTVERSION=	2.2.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Software Transactional Memory

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
