# New ports collection makefile for: hs-stm
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-stm/Makefile,v 1.4 2012/06/03 21:54:38 pgj Exp $
#

PORTNAME=	stm
PORTVERSION=	2.3
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Software Transactional Memory

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
