# New ports collection makefile for: hs-erf
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/math/hs-erf/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	erf
PORTVERSION=	2.0.0.0
PORTREVISION=	3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The error function, erf, and friends for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
