# New ports collection makefile for: hs-erf
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/math/hs-erf/Makefile,v 1.5 2011/05/26 00:51:06 ashish Exp $
#

PORTNAME=	erf
PORTVERSION=	2.0.0.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The error function, erf, and friends for Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
