# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/math/hs-erf/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	erf
PORTVERSION=	2.0.0.0
PORTREVISION=	13
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	The error function, erf, and friends for Haskell

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
