# New ports collection makefile for:	hs-tar
# Date created:		2010-08-17
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/archivers/hs-tar/Makefile,v 1.2 2011/05/26 00:50:52 ashish Exp $
#

PORTNAME=	tar
PORTVERSION=	0.3.1.0
PORTREVISION=	1
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell library for reading/writing/manipulating tar archives

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
