# New ports collection makefile for:	hs-tar
# Date created:		2010-08-17
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/archivers/hs-tar/Makefile,v 1.4 2012/06/03 21:23:44 pgj Exp $
#

PORTNAME=	tar
PORTVERSION=	0.4.0.0
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Reading, writing and manipulating ".tar" archive files

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
