# $FreeBSD$

PORTNAME=	iconv
PORTVERSION=	0.4.1.1
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	String encoding conversion

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
