# $FreeBSD$

PORTNAME=	iconv
PORTVERSION=	0.4.1.2
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	String encoding conversion

LICENSE=	BSD3CLAUSE

USES=		iconv:translit

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
