# New ports collection makefile for: hs-mmap
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-mmap/Makefile 300896 2012-07-14 13:54:48Z beat $

PORTNAME=	mmap
PORTVERSION=	0.5.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Memory-mapped files for POSIX and Windows

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
