# $FreeBSD$

PORTNAME=	http-attoparsec
PORTVERSION=	0.1.0
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Attoparsec parsers for http-types

LICENSE=	BSD

USE_CABAL=	attoparsec>=0.10.4.0 http-types>=0.8.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
