# $FreeBSD$

PORTNAME=	conduit
PORTVERSION=	1.1.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Streaming data processing library

LICENSE=	MIT

USE_CABAL=	lifted-base>=0.1 mmorph monad-control>=0.3.1 mtl \
		resourcet>=1.1 text>=0.11 transformers>=0.2.2 \
		transformers-base>=0.4.1 void>=0.5.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
