# $FreeBSD: head/devel/hs-prelude-extras/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	prelude-extras
PORTVERSION=	0.4
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Higher-order versions of Prelude classes

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
