# New ports collection makefile for: hs-vector-space
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/math/hs-vector-space/Makefile,v 1.4 2010/06/08 12:34:26 pgj Exp $
#

PORTNAME=	vector-space
PORTVERSION=	0.7.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Vector & affine spaces, linear maps, and derivatives in Haskell

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/COPYING

USE_HACKAGE=	Boolean>=0.0.1 MemoTrie>=0.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
