# New ports collection makefile for: hs-vector-space
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/math/hs-vector-space/Makefile 301904 2012-08-03 03:05:12Z pgj $
#

PORTNAME=	vector-space
PORTVERSION=	0.8.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Vector & affine spaces, linear maps, and derivatives in Haskell

LICENSE=	BSD
FILE_LICENSE=	COPYING

USE_CABAL=	Boolean>=0.0.1 MemoTrie>=0.5 NumInstances>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
