# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/math/hs-vector-space/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	vector-space
PORTVERSION=	0.10.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Vector and affine spaces, linear maps, and derivatives

LICENSE=	BSD3CLAUSE

USE_CABAL=	Boolean>=0.1.0 MemoTrie>=0.5 NumInstances>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
