# $FreeBSD$

PORTNAME=	parsers
PORTVERSION=	0.10.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parsing combinators

LICENSE=	BSD3CLAUSE

USE_CABAL=	charset>=0.3 parsec>=3.1 text>=0.10 transformers>=0.2 \
		unordered-containers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
