# $FreeBSD$

PORTNAME=	parsers
PORTVERSION=	0.12.2.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parsing combinators

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec>=0.12.1 charset>=0.3 parsec>=3.1 scientific>=0.3 \
		text>=0.10 unordered-containers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
