# New ports collection makefile for:	zlib
# Date created:				November 2, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: ports/archivers/hs-zlib/Makefile,v 1.10 2012/02/13 03:49:19 pgj Exp $

PORTNAME=	zlib
PORTVERSION=	0.5.3.3
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compression and decompression in the gzip and zlib formats

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
