# Created by: Samy Al Bahra <sbahra@kerneled.org>
# $FreeBSD: head/archivers/hs-zlib/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	zlib
PORTVERSION=	0.5.4.2
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compression and decompression in the gzip and zlib formats

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
