# New ports collection makefile for:	zlib
# Date created:				November 2, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: head/archivers/hs-zlib/Makefile 301879 2012-08-03 02:30:07Z pgj $

PORTNAME=	zlib
PORTVERSION=	0.5.3.3
PORTREVISION=	1
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compression and decompression in the gzip and zlib formats

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
