# $FreeBSD: head/devel/hs-memory/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	memory
PORTVERSION=	0.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Memory and related abtraction stuff

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
