# New ports collection makefile for: hs-data-accessor-mtl
# Date created:        April 8, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	data-accessor-mtl
PORTVERSION=	0.2.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Accessor to access state in mtl State monad class

LICENSE=	BSD

USE_CABAL=	data-accessor>=0.2 mtl>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
