# $FreeBSD$

PORTNAME=	data-accessor-mtl
PORTVERSION=	0.2.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Use Accessor to access state in mtl State monad class

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-accessor>=0.2 mtl>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
