# New ports collection makefile for: hs-hostname
# Date created:        May 21, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/net/hs-hostname/Makefile,v 1.3 2011/05/26 00:51:07 ashish Exp $
#

PORTNAME=	hostname
PORTVERSION=	1.0
PORTREVISION=	2
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform means of determining the hostname

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
