# New ports collection makefile for: hs-hostname
# Date created:        May 21, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: head/net/hs-hostname/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	hostname
PORTVERSION=	1.0
PORTREVISION=	4
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform means of determining the hostname

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
