# $FreeBSD$

PORTNAME=	fastirc
PORTVERSION=	0.2.0
CATEGORIES=	irc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast Internet Relay Chat (IRC) library

LICENSE=	BSD

USE_CABAL=	attoparsec>=0.8 bytestring-show>=0.3.3 monadLib>=3.6.1 network-fancy>=0.1.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
