# New ports collection makefile for: hs-shakespeare-i18n
# Date created:        December 31, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-shakespeare-i18n/Makefile,v 1.1 2012/02/18 17:30:46 pgj Exp $
#

PORTNAME=	shakespeare-i18n
PORTVERSION=	1.0.0.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A type-based approach to internationalization

LICENSE=	MIT

USE_CABAL=	parsec shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
