# New ports collection makefile for: hs-shakespeare-i18n
# Date created:        December 31, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-shakespeare-i18n/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	shakespeare-i18n
PORTVERSION=	1.0.0.2
PORTREVISION=	1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A type-based approach to internationalization

LICENSE=	MIT

USE_CABAL=	parsec shakespeare>=1.0 text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
