# $FreeBSD$

PORTNAME=	tagshare
PORTVERSION=	0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Explicit sharing with tags

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
