# $FreeBSD: head/devel/hs-monad-control/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	monad-control
PORTVERSION=	1.0.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Lift control operations through monad transformers

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers-base>=0.4.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
