# $FreeBSD: head/security/hs-Crypto/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	Crypto
PORTVERSION=	4.2.5.1
PORTREVISION=	9
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Collects together existing Haskell cryptographic functions

USE_CABAL=	HUnit QuickCheck>=2.4.0.1 random

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
