# $FreeBSD: head/converters/hs-sandi/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	sandi
PORTVERSION=	0.3.5
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD3CLAUSE

USE_CABAL=	conduit exceptions>=0.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
