# $FreeBSD: head/security/hs-crypto-cipher-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-cipher-types
PORTVERSION=	0.0.9
PORTREVISION=	2
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic cryptography cipher types

LICENSE=	BSD3CLAUSE

USE_CABAL=	byteable>=0.1.1 securemem>=0.1.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
