# New ports collection makefile for:	hs-attempt
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-attempt/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	attempt
PORTVERSION=	0.4.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Concrete data type for handling exceptions as failures

LICENSE=	BSD

USE_CABAL=	failure>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
