# New ports collection makefile for:	hs-attempt
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-attempt/Makefile,v 1.1 2012/02/18 16:17:25 pgj Exp $
#

PORTNAME=	attempt
PORTVERSION=	0.3.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Concrete data type for handling extensible exceptions as failures

LICENSE=	BSD

USE_CABAL=	failure>=0.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
