# $FreeBSD: head/devel/hs-hinotify/Makefile 412346 2016-04-01 14:00:51Z mat $

PORTNAME=	hinotify
PORTVERSION=	0.3.8.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell binding to inotify

LICENSE=	BSD3CLAUSE

LIB_DEPENDS=	libinotify.so:devel/libinotify

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
