# $FreeBSD: head/devel/hs-preprocessor-tools/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	preprocessor-tools
PORTVERSION=	1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Framework for extending Haskell's syntax via quick-and-dirty preprocessors

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=1 parsec>=3 syb>=0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
