# $FreeBSD$

PORTNAME=	word-trie
PORTVERSION=	0.3.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Implementation of a finite trie over words

LICENSE=	GPLv2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
