# New ports collection makefile for: hs-text
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-text/Makefile,v 1.4 2012/06/03 21:59:33 pgj Exp $
#

PORTNAME=	text
PORTVERSION=	0.11.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An efficient packed Unicode text type

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
