# New ports collection makefile for: hs-text
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-text/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	text
PORTVERSION=	0.11.2.0
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An efficient packed Unicode text type

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
