# New ports collection makefile for: hs-text
# Date created:        September 19, 2010
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-text/Makefile,v 1.3 2012/02/13 04:50:25 pgj Exp $
#

PORTNAME=	text
PORTVERSION=	0.11.2.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	An efficient packed Unicode text type

LICENSE=	BSD

USE_CABAL=	deepseq>=1.1.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
