# $FreeBSD$

PORTNAME=	network-fancy
PORTVERSION=	0.1.5.1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Networking support with a cleaner API

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
