# $FreeBSD$

PORTNAME=	network-fancy
PORTVERSION=	0.2.3
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Networking support with a cleaner API

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
