# $FreeBSD: head/devel/hs-profunctors/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	profunctors
PORTVERSION=	5.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Profunctors

LICENSE=	BSD3CLAUSE

USE_CABAL=	comonad>=4 distributive>=0.4.4 tagged>=0.4.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
