# $FreeBSD$

PORTNAME=	profunctors
PORTVERSION=	4.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Profunctors

LICENSE=	BSD3CLAUSE

USE_CABAL=	comonad>=4 semigroupoids>=4 tagged>=0.4.4 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
