# $FreeBSD: head/textproc/hs-hs-bibutils/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hs-bibutils
PORTVERSION=	5.5
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bindings to bibutils, the bibliography conversion utilities

LICENSE=	GPLv2

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
