# $FreeBSD$

PORTNAME=	ghc-pkg-lib
PORTVERSION=	0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Provide library support for ghc-pkg information

LICENSE=	BSD3CLAUSE

USE_CABAL=	ghc-paths>=0.1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
