# $FreeBSD$

PORTNAME=	iteratee
PORTVERSION=	0.8.9.6
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Iteratee-based I/O

LICENSE=	BSD3CLAUSE

USE_CABAL=	exceptions>=0.3 ListLike>=3.0 monad-control parallel>=2 \
		transformers-base>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
