# $FreeBSD$

PORTNAME=	iteratee
PORTVERSION=	0.8.9.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Iteratee-based I/O

LICENSE=	BSD

USE_CABAL=	ListLike>=3.0 monad-control MonadCatchIO-transformers>0.2 \
		parallel>=2 transformers>=0.2 transformers-base>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
