# $FreeBSD$

PORTNAME=	LDAP
PORTVERSION=	0.6.10
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell binding for C LDAP API

LICENSE=	BSD3CLAUSE

USE_OPENLDAP=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
