# New ports collection makefile for:	hs-mtl
# Date created:		2010-05-14
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-mtl-docs/Makefile,v 1.3 2012/02/13 03:49:25 pgj Exp $
#

PORTNAME=	mtl
PORTVERSION=	2.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for mtl

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	transformers>=0.3

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
