# $FreeBSD: head/devel/hs-List/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	List
PORTVERSION=	0.5.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	List monad transformer and class

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
