# New ports collection makefile for:	hs-regex-base
# Date created:		2010-08-10
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-regex-base/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	regex-base
PORTVERSION=	0.93.2
PORTREVISION=	4
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface API for regex-posix,pcre,parsec,tdfa,dfa

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
