# $FreeBSD: head/textproc/hs-regex-base/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	regex-base
PORTVERSION=	0.93.2
PORTREVISION=	14
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface API for regex-posix,pcre,parsec,tdfa,dfa

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
