# New ports collection makefile for:	hs-regex-base
# Date created:		2010-08-10
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-regex-base/Makefile,v 1.4 2012/06/03 20:52:25 pgj Exp $
#

PORTNAME=	regex-base
PORTVERSION=	0.93.2
PORTREVISION=	3
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Interface API for regex-posix,pcre,parsec,tdfa,dfa

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
