# $FreeBSD$

PORTNAME=	fay-ref
PORTVERSION=	0.1.0.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Like IORef but for Fay

LICENSE=	BSD3CLAUSE

USE_CABAL=	fay-base>=0.14.1.0

IGNORE_DYNAMIC=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
