# New ports collection makefile for: hs-base64-bytestring
# Date created:        August 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-base64-bytestring/Makefile,v 1.3 2012/06/03 21:34:40 pgj Exp $
#

PORTNAME=	base64-bytestring
PORTVERSION=	0.1.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base64 encoding and decoding for ByteStrings

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
