# $FreeBSD: head/devel/hs-base64-bytestring/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	base64-bytestring
PORTVERSION=	1.0.0.1
PORTREVISION=	8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base64 encoding and decoding for ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
