# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/converters/hs-json/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	json
PORTVERSION=	0.9.1
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for serialising Haskell to and from JSON

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl parsec syb>=0.3.3 text

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
