# New ports collection makefile for: hs-Boolean
# Date created:        June 5, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-Boolean/Makefile,v 1.2 2011/05/09 05:28:31 ashish Exp $
#

PORTNAME=	Boolean
PORTVERSION=	0.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generalized booleans

LICENSE=	BSD
FILE_LICENSE=	COPYING

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
