# $FreeBSD: head/devel/hs-Boolean/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	Boolean
PORTVERSION=	0.2.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generalized Booleans and numbers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
