# New ports collection makefile for: hs-pandoc-types
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/textproc/hs-pandoc-types/Makefile,v 1.4 2011/08/14 14:32:21 pgj Exp $
#

PORTNAME=	pandoc-types
PORTVERSION=	1.8.2
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Types for representing a structured document

LICENSE=	GPLv2
FILE_LICENSE=	COPYING

CABAL_SETUP=	Setup.hs
USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
