# New ports collection makefile for: hs-pandoc-types
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	pandoc-types
PORTVERSION=	1.8
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Types for representing a structured document

LICENSE=	GPLv2
LICENSE_FILE=	${WRKSRC}/COPYING

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
