# New ports collection makefile for: hs-pandoc-types
# Date created:        March 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-pandoc-types/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	pandoc-types
PORTVERSION=	1.9.1
PORTREVISION=	1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Types for representing a structured document

LICENSE=	GPLv2
FILE_LICENSE=	COPYING

CABAL_SETUP=	Setup.hs

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
