# $FreeBSD: head/textproc/hs-regex-applicative/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	regex-applicative
PORTVERSION=	0.3.2.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Regex-based parsing with applicative interface

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
