# New ports collection makefile for: hs-regex-tdfa
# Date created:        May 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	regex-tdfa
PORTVERSION=	1.1.8
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/Enhances Text.Regex

CABAL_SETUP=	Setup.hs

USE_CABAL=	mtl parsec regex-base>=0.93.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
