# Created by:	martin@sugioarto.com
# $FreeBSD: head/devel/hs-bytestring-lexing/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	bytestring-lexing
PORTVERSION=	0.5.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse and produce literals from strict or lazy bytestrings

LICENSE=	BSD2CLAUSE

USE_ALEX=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
