# $FreeBSD: head/security/hs-crypto-pubkey-types/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	crypto-pubkey-types
PORTVERSION=	0.4.3
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic cryptography Public keys algorithm types

LICENSE=	BSD3CLAUSE

USE_CABAL=	asn1-encoding asn1-types>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
