# New ports collection makefile for: hs-crypto-pubkey-types
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/security/hs-crypto-pubkey-types/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	crypto-pubkey-types
PORTVERSION=	0.1.1
PORTREVISION=	1
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic cryptography Public keys algorithm types

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	crypto-api>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
