# $FreeBSD: head/archivers/hs-zlib-enum/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	zlib-enum
PORTVERSION=	0.2.3.1
PORTREVISION=	2
CATEGORIES=	archivers haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Enumerator interface for zlib compression

LICENSE=	MIT

USE_CABAL=	enumerator>=0.4 zlib-bindings>=0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
