# New ports collection makefile for: hs-attoparsec-conduit
# Date created:        December 30, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/textproc/hs-attoparsec-conduit/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	attoparsec-conduit
PORTVERSION=	0.4.0.1
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Turn attoparsec parsers into sinks

LICENSE=	BSD

USE_CABAL=	attoparsec>=0.10 conduit>=0.4 text>=0.11 transformers>=0.2.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
