# $FreeBSD: head/devel/hs-STMonadTrans/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	STMonadTrans
PORTVERSION=	0.3.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad transformer version of the ST monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
