# New ports collection makefile for: hs-ieee754
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/math/hs-ieee754/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	ieee754
PORTVERSION=	0.7.3
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for dealing with IEEE floating point numbers

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
