# $FreeBSD: head/math/hs-ieee754/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ieee754
PORTVERSION=	0.7.6
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for dealing with IEEE floating point numbers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
