# New ports collection makefile for: hs-ieee754
# Date created:        April 7, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-ieee754/Makefile,v 1.1 2012/06/03 19:16:56 pgj Exp $
#

PORTNAME=	ieee754
PORTVERSION=	0.7.3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for dealing with IEEE floating point numbers

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
