# New ports collection makefile for: hs-MaybeT
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-MaybeT/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	MaybeT
PORTVERSION=	0.1.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for computations with failures

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
