# New ports collection makefile for: hs-MaybeT
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-MaybeT/Makefile,v 1.2 2012/06/03 20:52:08 pgj Exp $
#

PORTNAME=	MaybeT
PORTVERSION=	0.1.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Support for computations with failures

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
