# $FreeBSD$

PORTNAME=	streams
PORTVERSION=	0.8.2
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various Haskell 2010 stream comonads

LICENSE=	BSD

USE_CABAL=	comonad>=1.1.1.3 distributive>=0.2.1 semigroupoids>=1.3 \
		semigroups>=0.8.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
