# $FreeBSD$

PORTNAME=	streams
PORTVERSION=	3.2.1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various Haskell 2010 stream comonads

LICENSE=	BSD3CLAUSE

USE_CABAL=	adjunctions>=4.0.1 comonad>=4.0 distributive>=0.2.1 \
		semigroupoids>=4 semigroups>=0.8.3.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
