# $FreeBSD$

PORTNAME=	streams
PORTVERSION=	3.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various Haskell 2010 stream comonads

LICENSE=	BSD

USE_CABAL=	comonad distributive>=0.2.1 semigroupoids semigroups>=0.8.3.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
