# New ports collection makefile for: hs-comonad-tranformers
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/math/hs-comonad-transformers/Makefile,v 1.2 2012/02/13 05:06:55 pgj Exp $
#

PORTNAME=	comonad-transformers
PORTVERSION=	2.1.1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Comonad transformers

LICENSE=	BSD

USE_CABAL=	comonad>=1.1.1.3 contravariant>=0.2.0.1 distributive>=0.2.2 \
		semigroupoids>=1.3.1 semigroups>=0.8.2 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
