# New ports collection makefile for: hs-comonad-tranformers
# Date created:        July 16, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	comonad-transformers
PORTVERSION=	1.8.0
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Comonad transformers

LICENSE=	BSD

USE_CABAL=	comonad>=1.1 contravariant>=0.1.2 distributive>=0.2 \
		semigroupoids>=1.2.2 semigroups>=0.5 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
