# New ports collection makefile for: hs-cpu
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/sysutils/hs-cpu/Makefile,v 1.1 2012/06/03 19:23:57 pgj Exp $
#

PORTNAME=	cpu
PORTVERSION=	0.1.0
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cpu information and properties helpers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
