# $FreeBSD: head/sysutils/hs-cpu/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	cpu
PORTVERSION=	0.1.2
PORTREVISION=	2
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CPU information and properties helpers

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
