# New ports collection makefile for: hs-cpu
# Date created:        May 9, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/sysutils/hs-cpu/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	cpu
PORTVERSION=	0.1.1
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cpu information and properties helpers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
