# $FreeBSD$

PORTNAME=	free
PORTVERSION=	3.4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monads for free

LICENSE=	BSD

USE_CABAL=	bifunctors>=3 comonad>=3 comonad-transformers>=3 \
		comonads-fd>=3 distributive>=0.2.1 mtl>=2.0.1.0 \
		profunctors>=3.2 semigroupoids>=3 semigroups>=0.8.3.1 \
		transformers>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
