# $FreeBSD$

PORTNAME=	free
PORTVERSION=	4.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monads for free

LICENSE=	BSD3CLAUSE

USE_CABAL=	bifunctors comonad distributive>=0.2.1 mtl>=2.0.1.0 \
		profunctors semigroupoids semigroups>=0.8.3.1 \
		transformers>=0.2.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
