# New ports collection makefile for: hs-convertible-text
# Date created:        December 26, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-convertible-text/Makefile,v 1.1 2012/02/18 16:48:46 pgj Exp $
#

PORTNAME=	convertible-text
PORTVERSION=	0.4.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type classes and instances for converting between types

LICENSE=	BSD

USE_CABAL=	attempt>=0.3.0 text>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
