# $FreeBSD: head/devel/hs-mmorph/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	mmorph
PORTVERSION=	1.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Monad morphisms

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
