# $FreeBSD$

PORTNAME=	crackNum
PORTVERSION=	1.3
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Crack various integer, floating-point data formats

LICENSE=	BSD3CLAUSE

USE_CABAL=	data-binary-ieee754 ieee754

EXECUTABLE=	crackNum

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
