# New ports collection makefile for:	hs-system-filepath
# Date created:		December 30, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-system-filepath/Makefile,v 1.1 2012/06/03 19:12:30 pgj Exp $
#

PORTNAME=	system-filepath
PORTVERSION=	0.4.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	High-level, byte-based file and directory path manipulations

LICENSE=	MIT
FILE_LICENSE=	license.txt

CABAL_SETUP=	Setup.hs

USE_CABAL=	text>=0.7.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
