# $FreeBSD: head/devel/hs-data-pprint/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	data-pprint
PORTVERSION=	0.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Prettyprint and compare Data values

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2.0 parallel>=3.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
