# Created by: Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
# $FreeBSD: head/devel/hs-convertible/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	convertible
PORTVERSION=	1.1.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Typeclasses and instances for converting between types

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl old-locale old-time text>=0.8

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
