# New ports collection makefile for: hs-convertible
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-convertible/Makefile,v 1.8 2011/07/10 01:36:51 ashish Exp $
#

PORTNAME=	convertible
PORTVERSION=	1.0.11.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell type classes and instances for converting between types

LICENSE=	BSD

USE_CABAL=	mtl text>=0.7

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
