# $FreeBSD: head/net/hs-publicsuffixlist/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	publicsuffixlist
PORTVERSION=	0.1
PORTREVISION=	7
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Is a given string a domain suffix?

LICENSE=	BSD3CLAUSE

USE_CABAL=	cereal data-default text>=0.11 utf8-string

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
