# New ports collection makefile for: hs-arrows
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-arrows/Makefile,v 1.7 2012/02/13 03:49:21 pgj Exp $
#

PORTNAME=	arrows
PORTVERSION=	0.4.4.0
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell arrow classes and transformers

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	Stream

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
