# $FreeBSD$

PORTNAME=	haskell-generate
PORTVERSION=	0.2.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type-safe library for generating Haskell source code

LICENSE=	BSD3CLAUSE

USE_CABAL=	haskell-src-exts

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
