# $FreeBSD: head/sysutils/hs-ekg-json/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	ekg-json
PORTVERSION=	0.1.0.0
CATEGORIES=	sysutils haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	JSON encoding of ekg metrics

LICENSE=	BSD3CLAUSE

USE_CABAL=	aeson ekg-core>=0.1 text unordered-containers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
