# New ports collection makefile for: hs-cgi-hp
# Date created:        April 23, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD$
#

MASTERDIR=	${.CURDIR}/../hs-cgi

MAINTAINER=	haskell@FreeBSD.org

PKGNAMESUFFIX=	-hp

WITH_PLATFORM=	yes

.include "${MASTERDIR}/Makefile"
