# $FreeBSD$

PORTNAME=	wai-logger
PORTVERSION=	2.0.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Logging system for WAI

LICENSE=	BSD

USE_CABAL=	blaze-builder byteorder case-insensitive fast-logger>=2.0.0 \
		http-types network unix-time wai>=2.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
