# Created by: Kai Wang <kaiw27@gmail.com>
# $FreeBSD: head/devel/hs-BNFC/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	BNFC
PORTVERSION=	2.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Compiler front-end generator

LICENSE=	GPLv2

USE_CABAL=	mtl
USE_ALEX=	yes
USE_HAPPY=	yes

EXECUTABLE=	bnfc

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
