# $FreeBSD: head/devel/hs-MonadRandom/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	MonadRandom
PORTVERSION=	0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random-number generation monad

USE_CABAL=	mtl random transformers-compat>=0.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
