# $FreeBSD$

PORTNAME=	MonadRandom
PORTVERSION=	0.1.12
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Random-number generation monad

USE_CABAL=	mtl random transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
