# New ports collection makefile for:	hs-strict-concurrency
# Date created:		December 26, 2011
# Whom:			haskell@FreeBSD.org
#
# $FreeBSD$
#

PORTNAME=	strict-concurrency
PORTVERSION=	0.2.4.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Strict concurrency abstractions

LICENSE=	BSD

USE_CABAL=	deepseq>=1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
