# $FreeBSD$

PORTNAME=	deepseq
PORTVERSION=	1.3.0.2
CATEGORIES=	devel haskell

MAINTAINER=	max@FreeBSD.org
COMMENT=	Deep evaluation of data structures

LICENSE=	BSD

USE_CABAL=	array>=0.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
