# New ports collection makefile for: hs-http-date
# Date created:        June 10, 2012
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/www/hs-http-date/Makefile 300897 2012-07-14 14:29:18Z beat $
#

PORTNAME=	http-date
PORTVERSION=	0.0.2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP Date parser/formatter

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
