# $FreeBSD: head/www/hs-http-date/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	http-date
PORTVERSION=	0.0.6.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	HTTP Date parser/formatter

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
