# $FreeBSD: head/textproc/hs-regex-posix/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	regex-posix
PORTVERSION=	0.95.2
PORTREVISION=	9
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Replaces/enhances Text.Regex

LICENSE=	BSD3CLAUSE

USE_CABAL=	regex-base>=0.93

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
