# $FreeBSD$

PORTNAME=	type-level
PORTVERSION=	0.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type-level programming library

LICENSE=	BSD

USE_CABAL=	syb

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
