# Created by: Ju Pengfei <jupengfei@gmail.com>
# $FreeBSD: head/net/hs-pcap/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	pcap
PORTVERSION=	0.4.5.2
PORTREVISION=	9
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	System-independent interface for user-level packet capture

LICENSE=	BSD3CLAUSE

USE_CABAL=	network

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
