# $FreeBSD: head/devel/hs-logict/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	logict
PORTVERSION=	0.6.0.2
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Backtracking logic-programming monad

LICENSE=	BSD3CLAUSE

USE_CABAL=	mtl>=2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
