# New ports collection makefile for: hs-logict
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-logict/Makefile 301879 2012-08-03 02:30:07Z pgj $
#

PORTNAME=	logict
PORTVERSION=	0.5.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A backtracking logic-programming monad

LICENSE=	BSD

USE_CABAL=	mtl>=1.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
