# New ports collection makefile for: hs-logict
# Date created:        November 19, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-logict/Makefile,v 1.2 2012/06/03 21:51:06 pgj Exp $
#

PORTNAME=	logict
PORTVERSION=	0.5.0.1
PORTREVISION=	1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A backtracking logic-programming monad

LICENSE=	BSD

USE_CABAL=	mtl>=1.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
