# New ports collection makefile for: hs-ghc-paths-docs
# Date created:        July 09 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-ghc-paths-docs/Makefile,v 1.7 2012/02/13 03:49:23 pgj Exp $

PORTNAME=	ghc-paths
PORTVERSION=	0.1.0.8
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Documentation for ghc-paths

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

DOCUMENTATION=	yes

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
