# $FreeBSD: head/devel/hs-boxes/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	boxes
PORTVERSION=	0.1.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	2D text pretty-printing library

LICENSE=	BSD3CLAUSE

USE_CABAL=	split>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
