# $FreeBSD$

PORTNAME=	keys
PORTVERSION=	3.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Keyed functors and containers

LICENSE=	BSD

USE_CABAL=	comonad>=4 free>=4 semigroupoids>=4 semigroups>=0.8.3.1 \
		transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
