# $FreeBSD$

PORTNAME=	keys
PORTVERSION=	3.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Keyed functors and containers

LICENSE=	BSD

USE_CABAL=	comonad-transformers>=3 comonads-fd>=3 free>=3 \
		semigroupoids>=3 semigroups>=0.8.3.1 transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
