# $FreeBSD: head/devel/hs-old-time/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	old-time
PORTVERSION=	1.1.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Time library

LICENSE=	BSD3CLAUSE

USE_CABAL=	old-locale>=1.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
