# $FreeBSD$

PORTNAME=	irc
PORTVERSION=	0.5.1.0
CATEGORIES=	irc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	A small library for parsing IRC messages

LICENSE=	BSD

USE_CABAL=	parsec>=2.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
