# $FreeBSD$

PORTNAME=	irc
PORTVERSION=	0.6.1.0
CATEGORIES=	irc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Small library for parsing IRC messages

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
