# New ports collection makefile for: hs-checkers
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-checkers/Makefile,v 1.5 2011/05/09 05:28:34 ashish Exp $
#

PORTNAME=	checkers
PORTVERSION=	0.2.6
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Check properties on standard Haskell classes and data structures

USE_HACKAGE=	QuickCheck>=2.1.0.2

BROKEN=		does not compile

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
