# New ports collection makefile for: hs-checkers
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/devel/hs-checkers/Makefile,v 1.7 2011/08/14 11:25:29 pgj Exp $
#

PORTNAME=	checkers
PORTVERSION=	0.2.8
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Check properties on standard Haskell classes and data structures

LICENSE=	BSD
FILE_LICENSE=	COPYING

USE_CABAL=	QuickCheck>=2.3

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
