# $FreeBSD$

PORTNAME=	charset
PORTVERSION=	0.3.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast unicode character sets based on complemented PATRICIA tries

LICENSE=	BSD

USE_CABAL=	semigroups>=0.8.3.1 unordered-containers>=0.1.4.6

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
