# $FreeBSD: head/devel/hs-largeword/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	largeword
PORTVERSION=	1.2.3
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Provides a way of producing other large words

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
