# New ports collection makefile for: hs-largeword
# Date created:        July 13, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/devel/hs-largeword/Makefile,v 1.1 2012/02/13 02:19:28 pgj Exp $
#

PORTNAME=	largeword
PORTVERSION=	1.0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Provides a way of producing other large words

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
