# $FreeBSD: head/devel/hs-setenv/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	setenv
PORTVERSION=	0.1.1.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Cross-platform library for setting environment variables

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
