# $FreeBSD$

PORTNAME=	data-accessor-template
PORTVERSION=	0.2.1.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for accessing and manipulating fields of records

LICENSE=	BSD

USE_CABAL=	data-accessor>=0.1 utility-ht>=0.0.1

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
