# $FreeBSD: head/devel/hs-hspec-discover/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	hspec-discover
PORTVERSION=	2.1.10
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Automatically discover and run Hspec tests

LICENSE=	MIT

EXECUTABLE=	hspec-discover

OPTIONS_EXCLUDE=	DOCS

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
