# New ports collection makefile for:	hs-digest-ghc
# Date created:				January 22, 2009
# Whom:					Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/security/hs-digest/Makefile,v 1.9 2010/05/24 21:52:35 pgj Exp $
#

PORTNAME=	digest
PORTVERSION=	0.0.0.9
CATEGORIES=	security haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Efficient cryptographic hash implementations in Haskell

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
