# $FreeBSD$

PORTNAME=	string-qq
PORTVERSION=	0.0.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	QuasiQuoter for non-interpolated strings, texts and bytestrings

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
