# New ports collection makefile for: hs-terminfo
# Date created:        May 14, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: head/devel/hs-terminfo/Makefile 301899 2012-08-03 03:01:19Z pgj $
#

PORTNAME=	terminfo
PORTVERSION=	0.3.2.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell bindings to the terminfo library

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
