# New ports collection makefile for: hs-terminfo
# Date created:        May 14, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/devel/hs-terminfo/Makefile,v 1.5 2012/02/13 04:46:18 pgj Exp $
#

PORTNAME=	terminfo
PORTVERSION=	0.3.2.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Haskell bindings to the terminfo library

LICENSE=	BSD

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
