# $FreeBSD$

PORTNAME=	traverse-with-class
PORTVERSION=	0.1.1.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic applicative traversals

LICENSE=	MIT

USE_CABAL=	transformers

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
