# $FreeBSD$

PORTNAME=	traverse-with-class
PORTVERSION=	0.2.0.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic applicative traversals

LICENSE=	MIT

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
