# $FreeBSD$

PORTNAME=	type-eq
PORTVERSION=	0.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Type equality evidence you can carry around

LICENSE=	BSD3CLAUSE

USE_CABAL=	cpphs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
