# New ports collection makefile for:	bytestring-csv
# Date created:				November 25, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: head/textproc/hs-bytestring-csv/Makefile 301879 2012-08-03 02:30:07Z pgj $

PORTNAME=	bytestring-csv
PORTVERSION=	0.1.2
PORTREVISION=	8
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse CSV formatted data efficiently with Haskell

LICENSE=	BSD

USE_CABAL=	dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
