# New ports collection makefile for:	bytestring-csv
# Date created:				November 25, 2008
# Whom:					Samy Al Bahra <sbahra@kerneled.org>
#
# $FreeBSD: ports/textproc/hs-bytestring-csv/Makefile,v 1.10 2012/06/03 20:52:23 pgj Exp $

PORTNAME=	bytestring-csv
PORTVERSION=	0.1.2
PORTREVISION=	7
CATEGORIES=	textproc haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Parse CSV formatted data efficiently with Haskell

LICENSE=	BSD

USE_CABAL=	dlist

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
