# New ports collection makefile for: hs-dataenc
# Date created:        May 14, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/converters/hs-dataenc/Makefile,v 1.4 2011/05/09 05:28:30 ashish Exp $
#

PORTNAME=	dataenc
PORTVERSION=	0.14
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
