# New ports collection makefile for: hs-dataenc
# Date created:        May 14, 2010
# Whom:                Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD: ports/converters/hs-dataenc/Makefile,v 1.6 2012/02/13 04:05:48 pgj Exp $
#

PORTNAME=	dataenc
PORTVERSION=	0.14.0.3
CATEGORIES=	converters haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Data encoding library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
