# New ports collection makefile for: hs-base16-bytestring
# Date created:        May 25, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: head/devel/hs-base16-bytestring/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	base16-bytestring
PORTVERSION=	0.1.1.5
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base16 (hex) encoding and deconding for ByteStrings

LICENSE=	BSD

CABAL_SETUP=	Setup.hs

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
