# $FreeBSD: head/devel/hs-base16-bytestring/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	base16-bytestring
PORTVERSION=	0.1.1.6
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Fast base16 (hex) encoding and deconding for ByteStrings

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
