# $FreeBSD$

PORTNAME=	data-accessor
PORTVERSION=	0.2.2.3
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Utilities for accessing and manipulating fields of records

LICENSE=	BSD3CLAUSE

USE_CABAL=	transformers>=0.2

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
