# $FreeBSD$

PORTNAME=	ListLike
PORTVERSION=	4.1.0
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Generic support for list-like structures

LICENSE=	BSD3CLAUSE

USE_CABAL=	dlist>=0.7 fmlist>=0.8 text>=0.11 vector>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
