# New ports collection makefile for: hs-fgl
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: head/devel/hs-fgl/Makefile 300896 2012-07-14 13:54:48Z beat $
#

PORTNAME=	fgl
PORTVERSION=	5.4.2.4
PORTREVISION=	2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Martin Erwig Functional Graph Library

LICENSE=	BSD

CABAL_SETUP=	Setup.hs
USE_CABAL=	mtl

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
