# $FreeBSD$

PORTNAME=	graphviz
PORTVERSION=	2999.17.0.2
CATEGORIES=	graphics haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Bindings to Graphviz for graph visualisation

LICENSE=	BSD3CLAUSE

USE_CABAL=	colour dlist>=0.5 fgl>=5.4 polyparse>=1.9 temporary>=1.1 text \
		wl-pprint-text>=1.1.0.0

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
