# $FreeBSD: head/devel/hs-mutable-containers/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	mutable-containers
PORTVERSION=	0.3.2
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Abstactions and concrete implementations of mutable containers

LICENSE=	MIT

USE_CABAL=	mono-traversable primitive>=0.5.2.1 vector

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
