# $FreeBSD: head/www/hs-css-text/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	css-text
PORTVERSION=	0.1.2.1
PORTREVISION=	2
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSS parser and renderer

LICENSE=	BSD3CLAUSE

USE_CABAL=	attoparsec>=0.10.2.0 text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
