# New ports collection makefile for: hs-css-text
# Date created:        December 2, 2011
# Whom:                haskell@FreeBSD.org
#
# $FreeBSD: ports/www/hs-css-text/Makefile,v 1.1 2012/02/18 03:18:12 pgj Exp $
#

PORTNAME=	css-text
PORTVERSION=	0.1.1
CATEGORIES=	www haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	CSS parser and renderer

LICENSE=	BSD

USE_CABAL=	attoparsec>=0.10 text>=0.11

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
