# New ports collection makefile for: hs-category-extras
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/math/hs-category-extras/Makefile,v 1.4 2011/05/09 05:28:48 ashish Exp $
#

PORTNAME=	category-extras
PORTVERSION=	0.53.5
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various Haskell modules and constructs inspired by category theory

BROKEN=		obsolete

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
