# New ports collection makefile for: hs-category-extras
# Date created:        December 20 2009
# Whom:                Giuseppe Pilichi aka Jacula Modyun <jacula@gmail.com>
#
# $FreeBSD: ports/math/hs-category-extras/Makefile,v 1.3 2010/05/26 11:18:42 jacula Exp $
#

PORTNAME=	category-extras
PORTVERSION=	0.53.5
PORTREVISION=	1
CATEGORIES=	math haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Various Haskell modules and constructs inspired by category theory

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

BROKEN=		obsolete

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
