# $FreeBSD$

PORTNAME=	connection
PORTVERSION=	0.1.3.1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Simple and easy network connections API

LICENSE=	BSD

USE_CABAL=	certificate>=1.3.0 cprng-aes data-default network>=2.3 \
		socks>=0.4 tls>=1.0 tls-extra>=0.5

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
