# $FreeBSD: head/devel/hs-date-cache/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	date-cache
PORTVERSION=	0.3.0
PORTREVISION=	9
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Date cacher

LICENSE=	BSD3CLAUSE

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
