# $FreeBSD$

PORTNAME=	hse-cpp
PORTVERSION=	0.1
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Preprocess and parse Haskell code

LICENSE=	MIT

USE_CABAL=	cpphs haskell-src-exts>=1.14

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
