# $FreeBSD: head/devel/hs-stm-chans/Makefile 394918 2015-08-20 23:02:14Z pgj $

PORTNAME=	stm-chans
PORTVERSION=	3.0.0.4
CATEGORIES=	devel haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Additional types of channels for STM

LICENSE=	BSD3CLAUSE

USE_CABAL=	stm>=2.4

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
